### ISSUE TITLE
Refactor environment variable

### ISSUE THREAD

**Issue by cavo789** [thunderclient/thunder-client-support#1021]
Hello

Seems to be missing in your amazing tool: I've a global `url` variable in my `Env` tab. I've just renamed it `api_url` and .. all my test scenarios are KO now since my `{{url}}` variable has to be renamed to `{{api_url}}`.

![2023-02-21_12h49_54](https://user-images.githubusercontent.com/355999/220337262-219ae822-f4cc-4b39-be94-a83ce0e75131.png)

Would be really nice to f.i. get a prompt "Would you like to replace `{{url}}` to `{{api_url}}` everywhere?".

**Comment by rangav** [comment]
Thanks @cavo789 for the feedback, will look into it.

Alternatively you can open files `thunderclient.json` ( and `thunderactivity.json` ) and you can find and replace {{api}} to {{api_url}} easily.

**Comment by cavo789** [comment]
(like always, so fast!!!!)

Thanks!

**Comment by rangav** [comment]
closing this issue, currently not planning to implement
