### ISSUE TITLE
Can we have a feature of autosuggest end points which we have called in past

### ISSUE THREAD

**Issue by chhavibansal** [thunderclient/thunder-client-support#1025]
**Is your feature request related to a problem? Please describe.**
I dont want to remember the endpoints everytime, I would want to get suggestions after typing in some words of the endpoint, similar to how we have in postman.

**Describe the solution you'd like**
A list of endpoint similar to what i have typed in, which i have used in the past. I dont want the feature to be intelligent, it should just show me recommendations of similar endpoints i have hit in past

**Describe alternatives you've considered**
POSTMAN has this feature, right now in thunder client i have to remember the entire URL or save each endpoint in the collection and reopen each when i have to use or have to visit my history of curl calls i have made ( which is extremely time consuming)

**Your Team Size Using TC:**
[5]

[
<img width="1190" alt="Screenshot 2023-02-23 at 3 31 15 PM" src="https://user-images.githubusercontent.com/35660693/220876413-a5faa532-5c20-4233-8790-dfa125e7bf66.png">
]

**Comment by rangav** [comment]
Thanks @chhavibansal for the feedback, Will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to v2.8.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
