### ISSUE TITLE
Encrypted Environments feature feedback

### ISSUE THREAD

**Issue by rangav** [thunderclient/thunder-client-support#1269]
### Encrypted Environment feature
The environment variable values are stored in JSON files in plain text format. The encrypted environment feature will save variable values in an encrypted format, useful for additional security.

**#Stage:** Coming Soon

**#Price Plan:** Enterprise

**Please let us know your feedback:**

- How useful is this feature?
- When you export the environment, the values should be encrypted or not?

Based on the feedback and the number of users interested in this feature, we will add it to the roadmap.

**Comment by mjohl** [comment]
Want to make this enterprise, then have Azure KeyVault/AWS Key Management integration for sensitive values. Then you don't have to store the data and for export, only the reference to the KV secret is required, so not concerns there either.

**Comment by rangav** [comment]
We have implemented `Encrypted Environments` and `Integration with Secret Managers` in `v2.28.0`

Release Notes
https://github.com/thunderclient/thunder-client-support/releases/tag/v2.28.0

Please test and let me know your feedback.
