### ISSUE TITLE
Do environment variables support collections

### ISSUE THREAD

**Issue by Zy76278** [thunderclient/thunder-client-support#1392]
**Please describe feature/problem details and the solution you'd like.**
Now I have a chain request, and the later request needs the result of the previous request. Now I set an environment variable in the previous request and then use it in the request. But if there are more function modules, the variables in the environment will be too many, because the variables are in the same level, which is not easy to manage. Can environment variables be stored in different collections? I've learned that there can be multiple environments, but I need to execute these in one environment for now. Or is there any other way you can implement the case where the request requires the response parameters of the previous request.

      
**Describe alternatives you've considered**

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Hi @Zy76278  Currently not possible, you can save to env variables and delete variable as a cleanup process at the end from the last request.

**Comment by rangav** [comment]
Collection Level Variables are possible using scripting
- To use - open collection settings or request view -> then select `Pre Run` Tab and use the `Scripting` tab
```js
tc.setVar("name", "Thunder Client", "request");
tc.setVar("baseUrl", "http://localhost:8744", "request");
```

Docs Link
https://docs.thunderclient.com/features/environments
