### ISSUE TITLE
Option for not to sync params changes

### ISSUE THREAD

**Issue by evsar3** [thunderclient/thunder-client-support#1395]
**Please describe feature/problem details and the solution you'd like.**
Every time we have to make a test on one of the ThunderClient endpoints and we change the params of the request, it generates changes on the thunder-test folder.

**Describe alternatives you've considered**
I would like to suggest implementing some kind of params lock option, that prevents params changes to be synced with the files at thunder-tests. By "params lock option" I mean something that prevents the changes on the params to be synced with the thunder-tests files, not to disable params editing.

**Are you using the free version/paid version/trial:**
Paid version

**Comment by rangav** [comment]
Hi @evsar3 thanks for the feedback.

Alternative Option:

You can uncheck this setting, `Save Request on Send`, Then it wont change db files, until you explicitly save the request.

<img width="1107" alt="Screenshot 2023-11-07 at 21 10 48" src="https://github.com/rangav/thunder-client-support/assets/8637550/028e93dd-e270-4f06-8bf5-96e07e663ec8">

**Comment by rangav** [comment]
Closing this, as there is an existing option you can use it.

**Comment by evsar3** [comment]
I'm sorry not giving you a feedback, but the options have done what I needed.

Thank you.
