### ISSUE TITLE
Is there a way to get and set the data through script in collection run?

### ISSUE THREAD

**Issue by mrmaramreddy** [thunderclient/thunder-client-support#1404]
**Question:**
Is there an equivalent of postman`pm.iterationData.get` or `pm.iterationData.set` in TC to set or get values from csv when running a collection?

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
No we don't have similar API in TC

**Comment by rangav** [comment]
Can you please share your use-case and examples, We will review and add to the roadmap.

**Comment by mrmaramreddy** [comment]
My use case is, 

1. Create a csv file with user-friendly names.
2. Fetch these user-friendly names during "collection run" and parse the API response to fetch the corresponding id (lengthy and not user-friendly) for the respective user-friendly name.
3. Use the id fetched in step 2 in next API call which is part of the collection.
4. Repeat this process for all rows in the csv.

**Comment by rangav** [comment]
Thanks for sharing the use cases, Will review it.

**Comment by rangav** [comment]
pm.iterationData.get - > tc.getVar
