### ISSUE TITLE
Run Collection button stucks/freezes when pressed while Collection is being run

### ISSUE THREAD

**Issue by koynoyno** [thunderclient/thunder-client-support#1456]
**Describe the bug**
_Run_ button in _Run Collection_ window freezes on _Stopping..._ state when pressed while the collection is still running.

<img width="893" alt="Screenshot 2024-01-16 at 4 38 53 pm" src="https://github.com/rangav/thunder-client-support/assets/46102189/a9874508-731a-467e-8984-ad66d0a884c5">

**To Reproduce**
1. Collection that caused the issue: [thunder_bug_reproduce.json](https://github.com/rangav/thunder-client-support/files/13947238/thunder_bug_reproduce.json) (it uses local API, but the issue is not with the API).
2. Open _Collection > <name_of_the_collection> > Run All_ window
3. Press _Run_ button often, after several runs (~20 in my case) runs will sufficiently slow down, so you'll be able to hit the button while the collection still runs (see video below).

**Expected behavior**
_Run_ button is always available.

**Platform:** 
 - OS: macOS 14.1.2
 - vscode version: 1.85.1
 - extension version: 2.17.0

**Are you using the free version/paid version/trial:** free

**Why are you sure the problem with Thunder Client and not with the API?**
After the issue, I've run performance testing using Postman using the exact same collection, API endpoints were hit 1200 times during one minute and handled testing well.

**Comment by koynoyno** [comment]
Video: 

https://github.com/rangav/thunder-client-support/assets/46102189/efa023c6-d257-4030-8d4c-01dfcf86710e

For some reason, Thunder Client collection running became _way_ slower after 20+ subsequent runs. First 10 runs were instant, now it requires several seconds to stop running.

**Comment by rangav** [comment]
Hi @koynoyno 

The extension will try some additional initialization. But after that run collection should be as fast as normal.
