### ISSUE TITLE
Thunder client tabs close on reload

### ISSUE THREAD

**Issue by stefaanMLB** [thunderclient/thunder-client-support#1462]
**Describe the bug**
When a thunderclient windows is open in the editor groups and vscode is reloaded, all open editor tabs will reload except for the thunder client tabs

**To Reproduce**
Open a few editor tabs
Open a fex thundeclient tabs
press F1 + reload

**Expected behavior**
All open tabs should reload
However, the thunderclient tabs don't reload

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.85.2
 - extension version: v2.17.1

**Are you using the free version/paid version/trial:**
PAID version

**Comment by rangav** [comment]
Hi @stefaanMLB 

Thanks for feedback, will add to roadmap.

related to #680

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.21.15`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.21.15

Please test it and let me know your feedback

**Comment by rangav** [comment]
Hi All, We have disabled the Restrore Previous Tabs setting by default, Few users did not want this as default.

Please enable this setting, to activate this feature
<img width="535" alt="Screenshot 2024-05-26 at 11 10 48" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/b04494df-6848-4c76-8645-9277f00b8ae2">
