### ISSUE TITLE
ThunderClient is not responding to one of the API request and keeps spinning/rolling for infinite time.

### ISSUE THREAD

**Issue by mubeentajss** [thunderclient/thunder-client-support#1495]
Hello Team,

Am experiencing the API response spinning issue, When I hit the API request it keeps spinning infinitely and not showing any error response this happens only for one of our specific API request not for all, I see immediate response for negative scenario and not seeing response for happy path, same API request when I hit via cypress it shows response but through thunderClient I see it is rolling rolling until I have to close that tab otherwise it keeps spinning for infinite time, can someone please help on this ! thanks in advance !

**Comment by rangav** [comment]
can you please share the following

ext version
vscode version
node version

**Comment by mubeentajss** [comment]
N**ode.js v16.20.0.**

**Vscode verison** : **Version: 1.87.1 (Universal)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:23:16.418Z (6 days ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.6.0**

**Thunder Client version : v2.17.8**

**Comment by rangav** [comment]
Please update extension to latest version v2.19.5 and test it

**Comment by rangav** [comment]
Hi @TimWilsonQA 

Can you please contact us using this form, We need to investigate the issue
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
closing this as it's fixed in v2.20.3
