### ISSUE TITLE
Reduce merge conflicts

### ISSUE THREAD

**Issue by rangav** [thunderclient/thunder-client-support#1507]
@max-mykhailenko requested this feature.

> Do you plan to split database to multiple files? There are a lot of conflict when 10 backend developers working inside one collection and it's super hard to resolve conflict in files that takes 14k rows. Maybe you can also suggest some smart git settings that prevents it?

### Collection in UI
<img width="325" alt="Screenshot 2024-05-11 at 19 50 55" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/b44b1b3c-871c-4767-9cb0-f4b70b95e904">

### Database Design v3 (Current)
- One file per collection
<img width="321" alt="Screenshot 2024-05-11 at 19 36 52" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/cb877c5b-f01d-4ced-9fef-6d4c1eb7c5c7">

### NEW Database Design v4
- One file per request
<img width="321" alt="Screenshot 2024-05-11 at 19 46 01" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/a05be6f4-1daf-4c75-8dbe-81855e416342">

## How to upgrade to v4
- From command palette select -> `Upgrade Database to v4`
<img width="456" alt="Screenshot 2024-05-11 at 19 47 44" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/e1ff8bcc-97e3-4397-97e2-b653e1fd1b29">

## Downgrade to v3
- If you like downgrade back to v3 format, Please copy collection files from `_db-backupv3` back to `collections` folder

**Comment by rangav** [comment]
We will review this feature request and provide an update soon.

**Comment by cw1934** [comment]
My group is very interested in this feature, any update on the progress since last activity?

**Comment by rangav** [comment]
@cw1934 It's still in the research phase, We will provide an update soon in around 2-4 weeks.

**Comment by rangav** [comment]
We have implemented a new database design to reduce merge conflicts. Please upgrade to the new format and let us know your feedback.

**Comment by rangav** [comment]
@cw1934 @max-mykhailenko 

Can you please let us know your feedback on the NEW database design?

**Comment by max-mykhailenko** [comment]
@rangav We put this update into our roadmap. I hope in the next few weeks we will migrate

**Comment by cw1934** [comment]
@rangav We moved a couple solutions over today, and will continue to evaluate/test across multiple users and report back with any issues or comments.

**Comment by rangav** [comment]
@cw1934 thanks for the update.

we plan to support both v3 and v4 format. You can choose the format that suits your team.
