### ISSUE TITLE
Ability to take advantage of VSCodes floating window feature

### ISSUE THREAD

**Issue by CalvinWilkinson** [thunderclient/thunder-client-support#1509]
**Please describe feature/problem details and the solution you'd like.**

It would be amazing if we could drag(pull) the request windows off of VSCode and have it in its own window that could be put onto another monitor.  VSCode can be quite crowded as it is which is one reason why the floating window feature that was recently added was one if not the most requested feature of VSCode.

From a productivity and developer experience standpoint, I think this would be a great feature.

**Describe alternatives you've considered**

I do not have any other alternatives.

**Are you using the free version/paid version/trial:**
I am using the free version.

**Comment by rangav** [comment]
Thanks @CalvinWilkinson for the feedback, Will add to the roadmap

**Comment by CalvinWilkinson** [comment]
> Thanks @CalvinWilkinson for the feedback, Will add to the roadmap

Thanks for the reply and consideration!!

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.21.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.21.0

Please test it and let me know your feedback
