### ISSUE TITLE
ThunderClient Tests | reading of multiple files and setting to env.variables   

### ISSUE THREAD

**Issue by nurzhan-kukeyev** [thunderclient/thunder-client-support#1512]
**Question:** 
The question is: how can we read (readFile) more than one file in parameters and set contents of files to env.variables ? 

**Are you using the free version/paid version/trial:** 
paid user - collegue from erwin (deutsche bahn)

<img width="745" alt="image" src="https://github.com/thunderclient/thunder-client-support/assets/165887431/e78db4cb-51c8-4afe-993e-9f6e702a250d">

**Comment by Artem0ne** [comment]
In addition to the question: 
We want to get all .json files from project directory via JavaScript:

**Example:**

_In env variable where .json files stored:_ 
**myPath** = "D:\Folder"

_JavaScript:_
```
myPath= tc.getVar("myPath");
    const fs = require('fs');
    const path = require('path');
    fs.readdir(myPath, (err, files) => {
    if (err) {
        console.error('Error reading directory:', err);
        return;
    }
});
```

_JavaScript gives an error:_
```
Script Log: Error reading directory: {
  "errno": -4058,
  "code": "ENOENT",
  "syscall": "scandir",
  "path": "C:\\Users\\<user>\\AppData\\Local\\Programs\\Microsoft VS Code\\Folder"
}
```
JS uses the project folder of VS Code 

> C:\\Users\\<user>\\AppData\\Local\\Programs\\Microsoft VS Code


Question: How to pass from TC to JavaScript the correct path of the folder? Are there any ways?

**Comment by rangav** [comment]
You cannot read multiple files in the same test case in the UI.

from script it's possible, try using promises 

```js
const fs = require('fs').promises;

// Function to read directory
  try {
    // Directory path
    const directoryPath = tc.getVar('myPath')';

    // Read directory asynchronously with await
    const files = await fs.readdir(directoryPath);

    // List file names
    console.log('Files in the directory:');
    files.forEach(file => {
      console.log(file);
    });
  } catch (err) {
    console.log('Error reading directory:', err);
  }
```

**Comment by Artem0ne** [comment]
Hi Ranga, thanks for the fast reply. Unfortunately, this solution with premises didn't work for us:
![image](https://github.com/thunderclient/thunder-client-support/assets/59470703/ddf9e989-4563-4588-ab0a-6249ceb8d1a6)

JS takes the path where VSCode installed (C:\User...\Appdata)

Maybe other solutions?

**Comment by rangav** [comment]
Looks like the path is wrong
Ref - https://stackoverflow.com/a/43260706/4035948

can you open the path manually in explorer

**Comment by rangav** [comment]
I am closing this issue, feel free to continue discussion
