### ISSUE TITLE
Pressing "Enter"  key in  Update environment->Edit variable adds "hidden" space symbol and broke env  

### ISSUE THREAD

**Issue by amaxcz** [thunderclient/thunder-client-support#1515]
1. open env/Update environment
2. add new variable, and start edit it's value
3. at the end, press Enter to complete editing and submit new value
4. Enter keypress will add "invisible" [space] sybmbol at the end

so, its to easy broke env's just editing it (for now), and hard to detect where is an error

**Comment by rangav** [comment]
Thanks @amaxcz reporting the bug, can you please make you answers all questions of the template.

can you answer these questions 

**Platform:** 
 - OS: 
 - vscode version:
 - node version:
 - extension version:

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
This Bug is fixed and published to the marketplace. Please update to `v2.21.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.21.0

Please test it and let me know your feedback
