### ISSUE TITLE
Create a stop button to stop the ongoing request because some requests can take too much time without timeout and for sending new request after code update or request to another server user have to create new request in new tab

### ISSUE THREAD

**Issue by SH20RAJ** [thunderclient/thunder-client-support#1517]
**Please describe feature/problem details and the solution you'd like.**

Create a stop button to stop the ongoing request because some requests can take too much time without timeout and for sending new request after code update or request to another server user have to create new request in new tab
**Describe alternatives you've considered**

Create a stop button to stop the ongoing request because some requests can take too much time without timeout and for sending new request after code update or request to another server user have to create new request in new tab
**Are you using the free version/paid version/trial:**
Create a stop button to stop the ongoing request because some requests can take too much time without timeout and for sending new request after code update or request to another server user have to create new request in new tab

**Comment by rangav** [comment]
Closing issue, please answer issue template questions correctly
