### ISSUE TITLE
Ability to save SSE and WS Requests to collection

### ISSUE THREAD

**Issue by ohsnap27** [thunderclient/thunder-client-support#1522]
**Please describe feature/problem details and the solution you'd like.**
i would like to save SSE and WS to collection. This is currently only possible for Rest Requests. 

**Are you using the free version/paid version/trial:** Free version

**Comment by rangav** [comment]
Thanks @ohsnap27 for the feedback, Will review it.

**Comment by ohsnap27** [comment]
@rangav this feature request was marked as completed. will it be introduced in the next versions or was the request declined?

**Comment by rangav** [comment]
`Save to collection` option enabled for SSE and WS requests in `v2.32.0`

Please update and let me know if any feedback.
