### ISSUE TITLE
Pre Request Script: - Cannot read properties of undefined (reading 'json')

### ISSUE THREAD

**Issue by issam-seghir** [thunderclient/thunder-client-support#1523]
**To Reproduce**

I have two requests that I need help with. 

1. I need to send a request to `{{BASE_URL}}/test/forget`, which should return a JSON response similar to this:

```json
   {
     "token": "7c9e63633a28d3d1dd38cac478ec4fb1548e8fd4"
   }
```

2. I want to use the token obtained from the response of the first request in the path variable of the second request, like this:

   `{{BASE_URL}}/auth/reset/{{token}}
`
   The second request should return a JSON response as follows:

```json
   {
     "message": "Your password has been changed Successfully"
   }
```

To achieve this, I tried running a **pre-request**  to get the token from the first request `{{BASE_URL}}/test/forget`  , 

![image](https://github.com/thunderclient/thunder-client-support/assets/74573675/4bac03d4-750d-4fdb-9ccd-51aaea7e2938)

then use scripting to save the token in environment variables to use it in the second request  

![image](https://github.com/thunderclient/thunder-client-support/assets/74573675/542fd7ba-4ac2-41c0-a246-75b4e142e146)

but i get this error instead :

![image](https://github.com/thunderclient/thunder-client-support/assets/74573675/5894cf8e-cf7f-40a8-b7db-70eb5b96b21b)

**Platform:** 
 - OS: Windows 10 pro 22H2
 - vscode version:1.87.2
 - node version:20.10.0
 - extension version:v2.21.0

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
Please Move the script from Pre-Req to Tests tab

**Comment by issam-seghir** [comment]
even if i move the script to the test tab the response is comes from the **request** and not from the **prerequest** !
![image](https://github.com/thunderclient/thunder-client-support/assets/74573675/1eb71259-3c47-4b44-bff3-b3d40c0a2eb0)
![image](https://github.com/thunderclient/thunder-client-support/assets/74573675/f9ab452f-5f69-4cb7-a3cc-f830c1161b83)

**Comment by rangav** [comment]
change TOKEN word token

**Comment by issam-seghir** [comment]
Please focus on the main idea , Lowercase words won't affect it.

**Comment by rangav** [comment]
```js
var json = tc.response.json;
tc.setVar("token", json.token);
```

**Comment by rangav** [comment]
if you have more questions, please use StackOverflow for community support.
