### ISSUE TITLE
The responses from SSE are cut off

### ISSUE THREAD

**Issue by ohsnap27** [thunderclient/thunder-client-support#1524]
**Describe the bug**
The responses from SSE are cut off. 

**To Reproduce**
Create SSE Event:
GET https://sse.dev/test -> Connect
Output: 
_data: {"testing"_
**Expected behavior**
Full output is visible. in this case:
_data: {"testing":true,"sse_dev":"is great","msg":"It works!","now":1713165593684}_

**Platform:** 
 - OS: MacOS 14.3.1 (23D60)
 - vscode version:  1.88.0
 - node version: 18.18.2
 - extension version: v2.21.0

**Are you using the free version/paid version/trial:** free version.

![example_SSE_output](https://github.com/thunderclient/thunder-client-support/assets/49640596/fb6cd1bf-91b1-4e1b-a177-dab7b2bd8046)

**Comment by rangav** [comment]
Thanks @ohsnap27 for reporting the bug, Will fix it asap.

**Comment by rangav** [comment]
This bug is fixed now. please update to v2.21.3
