### ISSUE TITLE
Enable Right click and Run on the collections view

### ISSUE THREAD

**Issue by jenseralmeida** [thunderclient/thunder-client-support#1528]
**Please describe feature/problem details and the solution you'd like.**
In the same way we can do a right-click and then "Run All" on a collection, I'd like to be able to right-click and Run an individual request.

**Describe alternatives you've considered**
Open the Request by clicking on it, and then Run. The Right click would open and run on a single action.

**Are you using the free version/paid version/trial:**
Paid version

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.21.15`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.21.15

Please test it and let me know your feedback
