### ISSUE TITLE
Run Collection to use data files specified at Folder level

### ISSUE THREAD

**Issue by CharlieSnowCode** [thunderclient/thunder-client-support#1529]
I'm testing an API that has about a dozen unique Requests.  I would like each of those Request types to be tested using their own data file, so I assume each would need its own folder.  The Collection would have positive and negative cases and might look like:

Data Driven            (Collection)
- Positive Cases       (Folder)
     - Create                 (Folder, uses PositiveCreate.csv)
       - CreateObject    (Request)
     - Locate                 (Folder, uses PositiveLocate.csv)
       - LocateObject    (Request)

...
Setting different test data files at each folder is persisted, but when I Run All at the Collection level - none of the specified data files are used.  Is there a way to do this?  If not I would like to request it as a new feature.  Thank you!

We are using the paid version.

**Comment by rangav** [comment]
@CharlieSnowCode Thanks for the feedback, Currently not possible, Will review it.

Alternatively you can use scripting to read custom data files at request level and set variable values.

Can you try the scripting option and let me know your feedback.

**Comment by rangav** [comment]
- Copy the below script to your **folder settings** - **PreRun Scripting**
- change the variable name to your defined name

```js
var fileData = await tc.readFile("thunder-tests/test.csv");
var papaparse = require('papaparse');

var options = { delimiter: ',', quoteChar: '"', escapeChar: '"', header: true };
let csv = papaparse.parse(fileData, options).data;
console.log(csv);

var iteration = tc.info.currentIteration;

var iterationCsvData = csv[iteration];
if(iterationCsvData){
  console.log(iterationCsvData);
  var name = iterationCsvData["name"];
  console.log("name", name);

  // set variable using request scope so the value is not saved to active env file
  tc.setVar("name", name, "request");
}
```

**Comment by CharlieSnowCode** [comment]
I've attached the (Pre run) script and the .csv I'm using, a snapshot of the (Restful Booker) Request and of the output.  It seems like the script sees the file, but the Request is only executed once and none of the values are populated.
[preRunScript.txt](https://github.com/thunderclient/thunder-client-support/files/15098411/preRunScript.txt)
[BookerDataGood.csv](https://github.com/thunderclient/thunder-client-support/files/15098412/BookerDataGood.csv)
![Booking](https://github.com/thunderclient/thunder-client-support/assets/67278867/93f82157-a2fb-4f7c-b42b-e5afd3fe175a)
[Output.txt](https://github.com/thunderclient/thunder-client-support/files/15098442/Output.txt)

**Comment by rangav** [comment]
I just now tested the using the same request body and it worked for me
- used the same script and csv file
- script is used in collection settings pre-run scripting

<img width="1269" alt="Screenshot 2024-04-25 at 09 55 32" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/106e46c8-bc88-4a6c-b946-2b5cad5fe944">

**Comment by CharlieSnowCode** [comment]
Very interesting, I created a Collection and copied the script to it (I **_was_** using a folder inside an existing Collection which still doesn't work).  Then increased the Iterations to 3 and it worked.  Many thinks for your reply.
I would however still request the original feature be implemented, as this solution will have us creating 2 dozen Collections - which can't be executed from the UI all at once.  I'm sure they can be from the CLI, but the command would be a large paragraph.

**Comment by rangav** [comment]
For advanced use cases we recommend using scriping or cli is the best solution currently.

**Comment by rangav** [comment]
Closing this issue as you can achieve the functionality using scripting
