### ISSUE TITLE
Can't copy values from response headers

### ISSUE THREAD

**Issue by RickeyWard** [thunderclient/thunder-client-support#1531]
**Describe the bug**
Seems impossible to copy values from response headers

**To Reproduce**
Make a request, try to copy value from response headers

**Expected behavior**
selecting values and clicking copy / ctrl + c actually copies data

**Platform:** 
 - OS: windows 
 - vscode version: 1.88.1
 - node version: what? why is that relevant? 20.11.1
 - extension version: v2.21.16

**Are you using the free version/paid version/trial:**
Free

**Comment by bharatjcentrix** [comment]
@RickeyWard same here. I am unable to copy value too.

**Comment by rangav** [comment]
I have testing on mac and windows Ctrl+c is working.

Right click copy issue is vscode bug
- VS Code issue: https://github.com/microsoft/vscode/issues/141080

**Comment by RickeyWard** [comment]
Ctrl + c isn't working for me either. I'm on Windows 11. It might be a vscode issue I don't know how to check. But it made thunder client unusable for my current tasks 🙁

**Comment by RickeyWard** [comment]
Ctrl C works in every other program so idk why it would be a vscode specific ctrl+c issue, but restarting my computer did seem to help. 

Thanks for the help

I think I'd prefer an intentionally designed context menu with "copy key" "copy value" options instead of the default cut/copy/paste context that seems to not care about _context_ at all. Right clicking anywhere gives you the option to paste that does nothing and you can click copy when nothing is selected.

**Comment by rangav** [comment]
Thanks for the confirmation. 

Ctrl+c copy text functionality is also provided by vscode. if there is any other issues related to it, please report it to vscode team.

**Comment by rangav** [comment]
you can verify if its a vscode bug or not using below instructions
https://github.com/thunderclient/thunder-client-support/issues/1092#issuecomment-1490888852
