### ISSUE TITLE
Collection disappeared

### ISSUE THREAD

**Issue by janiel1806** [thunderclient/thunder-client-support#1536]
**Describe the bug**
Started vs code one morning my collection was nowhere to be found. 
I think it might be because of VS code update or because of Thunder client update. 

**To Reproduce**
Don't really know. 

**Expected behavior**
Expected to find my collection

**Platform:** 
 - OS: Windows 10
 - vscode version: latest
 - node version: n/a
 - extension version: latest

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
Just now fixed the bug. Please update to v2.22.1 version.
