### ISSUE TITLE
Oauth says "Saved Successfully" when it fails

### ISSUE THREAD

**Issue by awstlaur** [thunderclient/thunder-client-support#1537]
**Describe the bug**
Generating an Oauth token gives the popup "Saved Successfully" with green text despite failing.

**To Reproduce**
Under Auth -> Oauth2, send an oauth request with invalid credentials.
<img width="1006" alt="Screenshot 2024-05-07 at 7 49 56 AM" src="https://github.com/thunderclient/thunder-client-support/assets/8000562/6da528f3-e21a-4926-9ef7-ff40769e6555">

Observe the the success popup, but observe the following in the output:
```
OAuth2 Client Credentials Request: https://redacted.domain/oauth2/token
Request Method: POST
Request Headers:
{
  "Content-Type": "application/x-www-form-urlencoded"
}
Request Body:
grant_type=client_credentials&client_id=invalid_client_id&client_secret=invalid_client_secret

OAuth Response:
{
  "error_description": "Authorization failed. Invalid credentials",
  "error": "invalid_client"
}
```

**Expected behavior**
I expect a failure popup

**Platform:** 
 - OS: macOS Sonoma 14.4.1
 - vscode version: 1.89.0
 - node version: 18.18.2
 - extension version: v2.22.1

**Are you using the free version/paid version/trial:**
Free

**Comment by awstlaur** [comment]
This is still a bug on Thunder Client version v2.24.13

**Comment by rangav** [comment]
When you click generate token, the changes are saved and notified to user using message - Saved Sucessfully
