### ISSUE TITLE
Cannot Copy, Cut or Paste when you save a large query

### ISSUE THREAD

**Issue by LuisCode925** [thunderclient/thunder-client-support#1540]
**Describe the bug**
Within the extension you cannot  cannot copy, cut or paste the information if it's large (about 3,796 words)

**To Reproduce**
1.- Save a query with a lot of text, in my case it was a query to an LLM.
2.- Close and open VS Code. 
3.- Go to the saved queries , and try to copy, cut or paste within the extension
4.-  But if you previously copied a small query the problem would not arise, I duplicated the query and deleted some text to reduce its size and the options worked correctly

**Expected behavior**

**Platform:** 
 - OS: Windows 10 22H2
 - vscode version: 1.89.1
 - node version: 20.12.2
 - extension version: 2.22.1

**Comment by rangav** [comment]
@LuisCode925 could be a vscode bug - https://github.com/thunderclient/thunder-client-support/issues/1531#issuecomment-2083235346

**Comment by rangav** [comment]
Closing this issue, feel to continue discussion
