### ISSUE TITLE
Logout from all of my devices

### ISSUE THREAD

**Issue by broccolism** [thunderclient/thunder-client-support#1541]
**Question: Is there any way to log out from all devices?**

**Are you using the free version/paid version/trial: using Enterprise plan.**

Hi. I found that the terms of use changed as 3 devices limit for one account.
Since I have logged in on the device given from my company and returned it without logging out my account, I cannot log in on my new device.
Is there any way to log out from all of my devices? Thanks.

**Comment by rangav** [comment]
Hi @broccolism 

You can logout from the Manage Account menu

<img width="696" alt="Screenshot 2024-05-10 at 06 50 06" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/0c93d764-63f2-4502-a7ba-26243ae1dd88">


If you have any further questions, please contact support
https://www.thunderclient.com/contact

**Comment by broccolism** [comment]
@rangav Hi, my question was, is there any way to log out from ALL of my devices by logging out from one device.

**Comment by rangav** [comment]
@broccolism currently not possible to logout from all devices from the extension. 

Please contact support using below form
https://www.thunderclient.com/contact
