### ISSUE TITLE
Error "Update to latest version" shown although already updated to latest version (v2.23.1)

### ISSUE THREAD

**Issue by CPFLEEYENLONG** [thunderclient/thunder-client-support#1543]
**Describe the bug**
Error "Update to latest version"
"You are using an outdated extension" appear in v2.23.1, which is already latest version.

**To Reproduce**
- Open Thunder Client in VS Code
- Error occurs

**Expected behavior**
- No version outdated error message 

**Platform:** 
 - OS: Windows_NT x64 10.0.19045
 - vscode version: 1.89.1 
 - node version: 18.18.2
 - extension version: 2.23.1

**Are you using the free version/paid version/trial:** 
Free

**Comment by rangav** [comment]
Hi @CPFLEEYENLONG 

Please use the below steps
- Update extension to v2.23.2
- From command palette - Run `Debug Info` command
- Restart VS Code
- Now let me know what is the status?

**Comment by CPFLEEYENLONG** [comment]
after updated to v2.23.2, the error message changed to:
![image](https://github.com/thunderclient/thunder-client-support/assets/158981004/bf601dfe-a915-4b15-9af4-420f6ee67882)

**Comment by rangav** [comment]
The extension now validates the version by checking with our server.

looks like your server is blocking request to the our server.

you need to whitelist our domain `*.thunderclient.com`

**Comment by CPFLEEYENLONG** [comment]
thanks for the info

**Comment by rangav** [comment]
We have fixed the issue and removed the version check, Please update the extension to `v2.23.4`
