### ISSUE TITLE
CSV file uploaded is not reading in my query .

### ISSUE THREAD

**Issue by vikramboyadev** [thunderclient/thunder-client-support#1544]
**Question:**
I have collection which contains two request one is find the details and second one is update-details . I have csv file which contains around 10 rows of data.column name is id and it contains data and no other columns.
When I uploaded it and ran it's not reading the csv file 
In the thunderclient output log I can see only like below 

`{
    "query": {
        "terms": {
            "name.keyword": [
          "{{id}}"
            ]
        }
    },
    "_source": [
   <<somefileds>>
    ],
    "size": 20
}`

Expectation is in every iteration it should show the name exist in the csv file
**Are you using the free version/paid version/trial:** paid version

**Comment by rangav** [comment]
@vikramboyadev can you share your sample csv format?

**Comment by vikramboyadev** [comment]
file name ids2.csv content goes like this.here name is the id is the column name

id
vikram
vara
krishnaveni
mounikap
subbu
narasimha
srikanth
hari
surekha

**Comment by rangav** [comment]
The format is correct is correct.

can you also please confirm your company name using below form
https://www.thunderclient.com/contact

**Comment by vikramboyadev** [comment]
Done please check

**Comment by rangav** [comment]
Thanks @vikramboyadev for confirmation

Are you running the request directly or using the collection runner?

**Comment by vikramboyadev** [comment]
I am running using collection runner

**Comment by rangav** [comment]
Its working for me

<img width="1020" alt="Screenshot 2024-05-16 at 18 05 05" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/fb5e396f-f528-4176-9fc0-e71868e1ccd9">

**Comment by rangav** [comment]
[thunder-collection_Testing.json](https://github.com/thunderclient/thunder-client-support/files/15338687/thunder-collection_Testing.json)
[test.csv](https://github.com/thunderclient/thunder-client-support/files/15338691/test.csv)

Import the above collection and attach the csv in collection runner

**Comment by vikramboyadev** [comment]
The shared query collection is working but the collection I am using elastic queries to fetch the data I have same collection in postman its running perfectly fine.Due to some contrains I am not using it right now .

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html

GET /_search
{
  "query": {
    "terms": {
      "user.id": [ "kimchy", "elkbee" ],
      "boost": 1.0
    }
  }
}

Instead of  [ "kimchy", "elkbee" ], I am using reference column in the csv file .

```
{
  "query": {
    "terms": {
      "user.id": [ "{{name}}"]
    }
  }
"_source":[ ],
"size":30
}

In this case its not reading the csv file I did compared my collection with the shared one strange no changes on csv file or format or headers every thing looks same :(

**Comment by rangav** [comment]
You are using {{name}}. Is it not `{{id}}`?

**Comment by vikramboyadev** [comment]
That can be of {{id}} or {{name}} is the name of the column in the csv file.

**Comment by rangav** [comment]
We can do a call tomorrow, send me your availability in the email.

**Comment by vikramboyadev** [comment]
Please call me back any time betwen 10: AM IST to 6: PM IST

**Comment by vikramboyadev** [comment]
Please send me zoom link if you are available to the email id

**Comment by vikramboyadev** [comment]
Thank you Ranga I am able to fix the issue csv file I am using is not created properly .
 Open VS code --> add details like column name and data for that column and save the file as csv fixed my issue.Still a strange to me same input file is worked in postman tool.Thanks for sharing the information.
closing the issue here

**Comment by rangav** [comment]
Thanks Vikram, 

I will test by creating csv with sublime text and verify if there is any issue with formatting.
