### ISSUE TITLE
Dynamic variable syntax in JSON body

### ISSUE THREAD

**Issue by bombillazo** [thunderclient/thunder-client-support#1545]
**Please describe feature/problem details and the solution you'd like.**

Hello, there are cases where we'd like to have a value in the JSON body be dynamic, like when the value comes from the env, or we do not wish to hardcode and commit a value (like for password-related endpoints). This is what we'd like to have:

```ts
{
  "email": "example@domain.com",
  "password": "{{ENV_TEST_PASSWORD}}" // this if coming from env vars
  "password": "{TEST_PASSWORD}" // this if coming from local request vars (like the path vars)
}
```

**Describe alternatives you've considered**

Manually modify the JSON, but this is prone to error and could leak sensitive data via the saved collection requests.

**Are you using the free version/paid version/trial:**

Paid

**Comment by rangav** [comment]
@bombillazo this is already supported 

have you tested it?

**Comment by bombillazo** [comment]
No, but now I tried and you're right. I only saw for path variables in the documentation so it was misleading me.
