### ISSUE TITLE
Failed to Import: 1 files - thunder-collection-xyxyxyxyxy.json

### ISSUE THREAD

**Issue by dukaitamas** [thunderclient/thunder-client-support#1548]
**Question:**

**Are you using the free version/paid version/trial:** i use the version of the _**PAID**_ thunderclients vscode extnesion.
![tc](https://github.com/thunderclient/thunder-client-support/assets/66377339/50eb8512-058e-40d7-a9ca-b18e6090c599)

I did not know much about thunderclient, i used a free version of the tc , then it is stopped to working.
Then i have found out that the free version has limits.... so i decided to pay. (ofc at the free version you don't really mention much about the limits. I guess it would be FAIR if you would mention the LIMITS on the first page of your website and the vscode extension.
 As my exams coming close, i did not want to go for another api app, so i PAID a year subscription, but now i can not import thunderclient collections from github ZIP downloaded repositories, nor from import git url.

So how to make it to work? Also can i use it on multiple computers? I use roguhly 4 computers, 1 at home and 3 in the school, depends what classroom we work. Ofc i use only 1 computer at a time but in different locations (different classrooms).

I simply do not have time now to go to another platform ( postman etc) so if i paid a service i just want to use it. ;)

Thanks for your understanding. 

I hope you find me a quick solution for this.:)

**Comment by rangav** [comment]
@dukaitamas 

please contact our support using below form.
https://www.thunderclient.com/contact

**Comment by MehdiElMellali** [comment]
in the file json try to change the clientName to client
