### ISSUE TITLE
set-cookie from server supports or not?

### ISSUE THREAD

**Issue by ivanafanasyeu** [thunderclient/thunder-client-support#1549]
**Question:**
I'm setting cookies in golang, echo v4:
```go
	cookie := new(http.Cookie)
	cookie.Name = "Authorization"
	cookie.Value = tokenString
	cookie.Expires = time.Now().Add(24 * time.Hour)
	cookie.HttpOnly = true
	c.SetCookie(cookie)
```

I'm doing /api/login and in response I have authorization cookies.
![Screenshot 2024-05-26 at 14 57 42](https://github.com/thunderclient/thunder-client-support/assets/25664253/496d3089-553c-48e6-b3fd-5ade3eed8e83)
![Screenshot 2024-05-26 at 14 58 00](https://github.com/thunderclient/thunder-client-support/assets/25664253/c181adea-752f-4acc-8174-fd1c07b4738b)
But I don't see any cookies in the get request, meanwhile if I click manage cookies, they are there
![Screenshot 2024-05-26 at 14 58 49](https://github.com/thunderclient/thunder-client-support/assets/25664253/d8a8067e-555a-48f1-a319-dfc0cfc43539)

Anything I'm missing or don't understand, or this behaviour is not supported, and I need manually copy those cookies into the headers?

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
see - https://docs.thunderclient.com/

**Comment by ivanafanasyeu** [comment]
> see - https://docs.thunderclient.com/

And where? Cookie page doesn't reveal anything about it. It says about headers, and pre scripts, but it has nothing to do with testing on real code. If I'm blind, show me please. It definitely not on the main page, and I don't see any revealing information about my particular question in the cookie section

**Comment by rangav** [comment]
@ivanafanasyeu if you have more questions please post on StackOverflow for community support or purchase a paid version to get support from TC team.
