### ISSUE TITLE
Get Request ID

### ISSUE THREAD

**Issue by mjohl** [thunderclient/thunder-client-support#1554]
**Question:**

**Are you using the free version/paid version/trial:** PAID Version

According to the [documentation](https://docs.thunderclient.com/scripting/send-request#send-internal-requests), you can do the following:

`var result = await tc.runRequest("reqId");`

### My question is the following: 
How do I get the **"reqId"** of the other request? The UI has no way of getting it to my knowledge and having to export the collection the whole time to get ID's are super annoying.

**Comment by rangav** [comment]
@mjohl thanks for feedback, Will display id in the UI.

you can get id using below code
`console.log(tc.request.id)`

**Comment by mjohl** [comment]
@rangav Looking forward to the improvement. The better improvement would be to call the other request by "Name". 
So instead of: `var result = await tc.runRequest("reqId");`
We could use: `var result = await tc.runRequest("Get All Members");`

It would make the readability a lot better, but I understand the complexity behind this as you now have to find the request in the collection.

The trophy solution would be a second optional parameter where I can call a request from another collection:
`var result = await tc.runRequest("Run Request A", "From Coll A");`

**Comment by rangav** [comment]
Request id is displayed in the Pre-Run tab
<img width="759" alt="Screenshot 2024-11-03 at 19 28 27" src="https://github.com/user-attachments/assets/2d37a2d1-f7de-4afd-a0bf-24750abca5d4">

**Comment by mjohl** [comment]
@rangav Thank you for the. Small niggle that it copies the GUID along with a newline character, but a lot of systems do that, so used to it pressing ctrl+v then backspace.
