### ISSUE TITLE
Add a simple way to get the complete request that will be send

### ISSUE THREAD

**Issue by ahourlier** [thunderclient/thunder-client-support#1561]
**Please describe feature/problem details and the solution you'd like.**
If i want to get a textual representation of the request i made, i have to go through each 'Query', 'Headers', 'Body' panel, and copy paste each content one next to the other.
Would be nice to have a way to get all informations more easily.

**Describe alternatives you've considered**
A 'Copy Request' button which would copy whole request at once into clipboard.
OR
A 'Global' or 'Resume' panel which displays the whole request at once (Including URL, query, headers, body) 
 

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
You can see request details in logs
https://docs.thunderclient.com/features/logs

**Comment by ahourlier** [comment]
Woop, was hard to miss that, thanks
