### ISSUE TITLE
PKCE State Param

### ISSUE THREAD

**Issue by m-schrepel** [thunderclient/thunder-client-support#1566]
**Please describe feature/problem details and the solution you'd like.**
The state parameter of the PKCE flow should be something random that only the caller knows about to ensure no one has intercepted a request within the oAuth2 flow. 

What I'd like is for `{{#guid}}` to work in the state field within the Authorization tab

**Describe alternatives you've considered**
Tried setting an env var like `UUID: {{#guid}}` but this only appears to work param and body fields. 

**Are you using the free version/paid version/trial:**
Enterprise customer

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.25.7`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.25.7

Please test it and let me know your feedback
