### ISSUE TITLE
The request cannot be moved to another folder

### ISSUE THREAD

**Issue by AlekStyk** [thunderclient/thunder-client-support#1567]
The problem has never happened before.

I have a problem with moving folders, requests and collections in the project tree. 
I can't change the order. When you try to move a request, it **IS NOT HIDGHLIGHTED** as in the screenshot.
![obraz](https://github.com/thunderclient/thunder-client-support/assets/121045962/e0c87ea2-302e-43a0-98e8-8c5cf90a89bd)

Has TC freezed or maybe my VSC settings are incorrect? Can you provide some help with it?

**paid version**

**Comment by rangav** [comment]
@AlekStyk please restart vscode and try again

**Comment by rangav** [comment]
Thanks for sharing video.

what is the vscode version?

**Comment by AlekStyk** [comment]
Version: 1.91.0 (user setup)
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by rangav** [comment]
We haven't changed anything in sorting feature, so could be a vscode issue.

try downgrade of vscode to 1.90 or lower.

we will also investigate the issue

**Comment by AlekStyk** [comment]
For now that helps. Thank you. I downgrade my VSCode to version 1.90.2 

If you have any information, please let me know! Thank you!

**Comment by rangav** [comment]
Its a vscode bug 
Ref - https://github.com/microsoft/vscode/issues/219047

**Comment by stefanfrings2** [comment]
The problem was resolved in vscode 1.91.0 but it occurs again in version 1.92.0

**Comment by rangav** [comment]
@stefanfrings2 Please report to vs code team

**Comment by stefanfrings2** [comment]
Reported to the vscode team. I just wanted to mention the version number here for people searching for help.

**Comment by rangav** [comment]
The is fixed in vscode update `v1.92.1`
