### ISSUE TITLE
I am no longer able to move requests or folders with drag&drop

### ISSUE THREAD

**Issue by checkerix** [thunderclient/thunder-client-support#1569]
**Describe the bug**
I recently received a new license (upgrade from Business to Enterprise)
shortly afterwards I noticed that I can no longer move requests or folders using drag & drop
not sure if it is related to the license change, but for my colleagues with the Business license it still works

**Platform:** 
 - OS: Windows 10 Home 22H2
 - vscode version: 1.91.0
 - node version: 20.9.0
 - extension version: v2.24.12

**Are you using the free version/paid version/trial:**
paid (Enterprise)

**Comment by garkpit** [comment]
Me too - same issue - very annoying!

**Comment by rangav** [comment]
@garkpit this is a vscode bug https://github.com/thunderclient/thunder-client-support/issues/1567#issuecomment-2210676998

**Comment by garkpit** [comment]
Okay - thank you
