### ISSUE TITLE
Skip request is not working both on cli running or collection running usaing UI

### ISSUE THREAD

**Issue by thiagosouza** [thunderclient/thunder-client-support#1575]
**Describe the bug**
I need to skip some requests in my tests. So I am trying the skip request functionality, but it is not working. I verified everything I could with no success.

**To Reproduce**
create two requests and in the first one add a pre-request script with the following code

```
if(someReasonToSkip)
  await tc.skipRequest(tc.request.id);
```

**Expected behavior**
It was supposed to not execute the second request, but it is running it anyways.

**Platform:** 
 - OS: Windows
 - vscode version: 1.19.1.1
 - node version: 20
 - extension version: v2.24.12

**Are you using the free version/paid version/trial:** 
paid

**Comment by rangav** [comment]
@thiagosouza thanks for reporting the bug, Will verify and get back to you asap.

**Comment by rangav** [comment]
I just now tested it's working.

Can you please create a sample collection and export and share the file.
