### ISSUE TITLE
When using inside a devcontainer, thunderclient cannot persists the existing requests list, if we rebuild the container

### ISSUE THREAD

**Issue by rv-nath** [thunderclient/thunder-client-support#1577]
When used inside of a devcontainer, the extension cannot retain the created requests list, when we rebuild the container.  As per copilot's suggestions, I have added the following settings. But still no luck.
```json
"customizations": {
		"vscode": {
			"extensions": [
				"rangav.vscode-thunder-client",
				"Github.copilot"
			],
			"settings": {
				"thunder-client.storagePath": "/workspace/.thunderclient"
			}
		}
	},
```

In spite of this, it can't retain or reload the requests data from storage.

**To Reproduce**

- Select thunderclient on the left side panel.
- click new request
- Create any http request and send it, to ensure it gets shown on the left sidebar
- Rebuild the container
- Reopen the thunderclient and observe the list of requests.

**Expected behavior**

We should be able to see the previously created bookmark of request.
**Platform:** 
 - OS:  Ubuntu24
 - vscode version: 1.91.1
 - node version:  do you mean Nodejs:  
 - extension version:  2.24.13

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Please use team collaboration settings 
https://docs.thunderclient.com/team
