### ISSUE TITLE
TC CLI: save response body in file

### ISSUE THREAD

**Issue by raShMan777** [thunderclient/thunder-client-support#1578]
We're currently in the process of building a GitLab CI/CD pipeline for exporting data from our monitoring system and writing them into a repo.
So now I discovered that the TC CLI doesn't have the feature of saving the response body to a file.
While I'm capable of piping the output of `tc` to save the response body:
Is there a way to do this in a better/cleaner way e.g. with scripting in the request?

We're using the paid version in our company.

**Comment by rangav** [comment]
Hi @raShMan777 

can you please confirm your subscription using below form
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
You can use the below script in Tests -> Scripting tab

```js
const fs = require('fs');

var data = tc.response.text;
console.log(data);

fs.writeFileSync("/Users/ranga/Downloads/response.txt", data);

```

**Comment by raShMan777** [comment]
cool, thx.
will test it on wednesday and give feedback but so far it look like an adequate solution.

**Comment by raShMan777** [comment]
thx, works as expected and needed. closing this.
