### ISSUE TITLE
Add option to CLI to re-generate oauth token

### ISSUE THREAD

**Issue by NeariX67** [thunderclient/thunder-client-support#1579]
**Describe the bug**
My requests fail using the CLI, but are fine running in VSCode. I'm asuming this is because the CLI has an old OAuth Token with wrong permissions. It's easy to generate a new token in the UI (which is not shared with CLI) but there is no option to do the equivalent with the CLI.

**To Reproduce**
- Create a request and configure oauth with insufficient permissions (scope)
- Run request in CLI
- Re-configure Oauth with sufficient permissions (scope)
- Re-Run request in CLI (still fail because same token)

**Expected behavior**
Re-run token generation on configuration change or before collection is run

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.19.1
 - node version: 19.4.0
 - extension version: v2.24.13
 - cli version: 1.16.2

**Are you using the free version/paid version/trial:**
Trial

**Comment by rangav** [comment]
@NeariX67 

please generate token from OAuth tab first in the UI.

then run in CLI it will work.

**Comment by NeariX67** [comment]
Auth code does not change in CLI when generating a new token using the UI.

**Comment by rangav** [comment]
It will use the same code until expiry and generate a new token after expiration

**Comment by NeariX67** [comment]
i don't want to wait until expiry.

**Comment by rangav** [comment]
what Grant Type are you using?
<img width="531" alt="Screenshot 2024-07-26 at 18 48 06" src="https://github.com/user-attachments/assets/674972fb-b09a-454b-b4f9-9bf84b3d5d00">

**Comment by NeariX67** [comment]
Client Credentials

**Comment by rangav** [comment]
currently not possible to generate new token on every request, only generate new on expiry
