### ISSUE TITLE
Getting CLI error - failed Unknown language: "text"

### ISSUE THREAD

**Issue by db-pw-rocker** [thunderclient/thunder-client-support#1581]
**Describe the bug**
we are getting an error in CLI failed Unknown language: "text" with Version: 1.15.8.
In Thunderclient in locally everything is working and the error is no visible in the logs....

**To Reproduce**
???
Our guess:
Getting a response in plain text from an API.

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:v2.24.13
 - node version:
 - extension version:
1.15.8.
**Are you using the free version/paid version/trial:**

Log
Request URL:  POST - https://{placeholder]/api/v1/routes
Environment:  TEST_ENV (Active)
Response 
Error - Request Send {placeholder] failed Unknown language: "text"

**Comment by db-pw-rocker** [comment]
using paid version

**Comment by rangav** [comment]
Hi @db-pw-rocker thanks for reporting bug.

can you please test with previous version of CLI?

**Comment by db-pw-rocker** [comment]
does not work with previous version either.
tested on Version: 1.13.2 (CLI)

**Comment by rangav** [comment]
Can you test the request with Extension UI and let me know

**Comment by db-pw-rocker** [comment]
hi,
with Extension UI it does work and I cannot see the any error in the logs..
The test itself does not fail (not in UI and not in CLI).
but CLI logs an error message (and pipeline fails).... 

Actual log in CLI
Request URL:  POST - PLACEHOLDER
Environment:  TEST_ENV (Active)
Response 
Error - Request Send (PLACEHOLDER) failed Unknown language: "text"
Reports
...

Expected:
Request URL:  POST - PLACEHOLDER
Environment:  TEST_ENV (Active)
Response 
"HelloWorld" <- text response from the request
Reports
...

**Comment by rangav** [comment]
Thanks for the confirmation 

does any url work with CLI or all urls are failing?

Is possible to share screenshots of the CLI error?

**Comment by db-pw-rocker** [comment]
there is not more error message.

as I mentioned above, it seems like, that CLI cannot work with an url endpoint with plain/text as a repsonse (content type)..
the CLI tries to log always the response for any request. and in the case of sending a request and getting a plainText reponse, the CLI logs the error "Unknown language "text".

could you try to reproduce the issue please? :)


(is there an option in the ui to get more logs than the "output thunderclient" ?
![image](https://github.com/user-attachments/assets/eac96e61-c3df-4fdb-aaad-b5e0c9f58607)

**Comment by rangav** [comment]
Thanks, I can reproduce the bug for text response in CLI, Will fix it asap.

**Comment by db-pw-rocker** [comment]
perfect,  great news :)
thanks

**Comment by rangav** [comment]
I have fixed the bug and published a new CLI version v1.16.3. 

Please update and test it.

**Comment by db-pw-rocker** [comment]
fix worked, thanks!
