### ISSUE TITLE
Issue with fonts after import from url

### ISSUE THREAD

**Issue by jpmitri** [thunderclient/thunder-client-support#1584]
**Describe the bug**
After importing from URL an Open-API V3.0.1 file i got some issues with the typography witch render me unable to use the plugin

![image](https://github.com/user-attachments/assets/5241515c-1746-4d41-a842-92fbf8026327)

as you can see in the picture when i double click on an item it highlights where the item is actually but visually the item is someplace else 

The font i am using is CaskaydiaCove Nerd Font Propo SemiLight

**To Reproduce**
Import any API from swagger using .net8 default API weather-app should reproduce the same

**Platform:** 
 - OS: Windows 11 
 - vs-code version: 1.92
 - node version: v20.15.1
 - extension version: v2.24.13

**Are you using the free version/paid version/trial:**
Paid Single User License

**Comment by rangav** [comment]
Could be custom font issue

see here - https://github.com/thunderclient/thunder-client-support/issues/1326#issuecomment-1714123998

**Comment by jpmitri** [comment]
I will change the font and get back to you
Dose it work with mono space if i wanted to use Microsoft Terminal font Cascadia Mono?

And in that case if i put multiple fonts in vs code will it fall back to the second font if the first one is not compatible?

**Comment by rangav** [comment]
I am unsure how it will perform with multiple fonts. Please test it and see which font works.
