### ISSUE TITLE
New Request action not working

### ISSUE THREAD

**Issue by mssanjay** [thunderclient/thunder-client-support#1588]
**Describe the bug**
Upon clicking New Request, nothing happens. I see a log message "Please Login to perform this action"
I even logged into my account. Is this completely paid version now?

**To Reproduce**
Click New Request

**Expected behavior**
- Show New Request Screen

**Platform:** 
 - OS: Windows 10
 - vscode Version: 1.92.2 (user setup)
 - node version: 20.14.0
 - extension version: v2.24.13

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
@mssanjay not sure what paid features you using.

Please video recording of the issue

**Comment by rhclayto** [comment]
I have the same problem. I click 'New Request', nothing happens except 'Please login to perform this action' in the output panel. Free version. I can't perform any requests. I was able to for a while but then it stopped working.
