### ISSUE TITLE
After upgrade vscode extension.The request history  lost

### ISSUE THREAD

**Issue by xiaobaxiang** [thunderclient/thunder-client-support#1590]
**Describe the bug**

After i upgrade vscode extension.The request history  lost
**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: window10
 - vscode version:1.92.2
 - node version: v21.5.0
 - extension version: v2.24.13

**Are you using the free version/paid version/trial:**
![image](https://github.com/user-attachments/assets/43b1d364-2e85-425f-ae2a-f7873df6dc46)

**Comment by rangav** [comment]
Hi @xiaobaxiang 

did you use git sync settings?
https://docs.thunderclient.com/team

Also please see Note 3 in the above link.

**Comment by rangav** [comment]
closing this issue, need more info.
