### ISSUE TITLE
Replace URL shortcut in folder

### ISSUE THREAD

**Issue by FMorschel** [thunderclient/thunder-client-support#1592]
**Please describe feature/problem details and the solution you'd like.**
I'd like an easier solution to replacing all URLs for a folder. I was not using env variables before and I'd like to start using it but now I need to go through every request and change the url.

**Are you using the free version/paid version/trial:**
I'm using the free version for now.

**Comment by rangav** [comment]
Thanks for the feedback, We are not planning to add this feature.
