### ISSUE TITLE
Option to rename variable

### ISSUE THREAD

**Issue by FMorschel** [thunderclient/thunder-client-support#1593]
**Please describe feature/problem details and the solution you'd like.**
Whenever you change a variable name you need to go through all of your requests to rename them there as well. I'd like a way for me to rename the variable name and it would refactor all of my existing requests that are using it.

**Are you using the free version/paid version/trial:**
I'm currently using the free version.

**Comment by FMorschel** [comment]
Partially inspired by https://github.com/thunderclient/thunder-client-support/issues/1592

**Comment by rangav** [comment]
Not planning to implement this, You can use the paid version to solve this issue, then you can find replace in vscode
