### ISSUE TITLE
Open Env (Active) should update when modified

### ISSUE THREAD

**Issue by ericm301** [thunderclient/thunder-client-support#1595]
**Please describe feature/problem details and the solution you'd like.**

I am using an API that has me refresh an access token every 20 minutes. I do this reqularly as I'm sending requests.
The GetNewToken request modifies the env to set the token to the new value, then the rest of the collection can use the token.

But, if I have the active environment open in a tab, this tab never updates to reflect the change. There's no indication that the tab is stale, and no way to refresh the tab without closing the env tab and opening it again.
- NOTE: the open (stale) Env tab does not interfere with the other requests. They are able to use the new value for the access token.

#### My solution
Add a `RELOAD` button, so I don't have to close and open the tab.
There could also be a checkbox, similar to `[o] refresh after request`, that would enable the tab to do this automatically.
A really cool implementation would be to highlight the individual variables on the tab that have changes, and have a button to0 refresh them, same as the hide and delete buttons.

**Describe alternatives you've considered**
I've just been closing and opening the Env tab.

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
The library is updated and the new version is published to the marketplace. Please update to `v2.29.10`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.29.10

Please test it and let me know your feedback
