### ISSUE TITLE
VS Code plugin: Ability to save the current request (with all details) in a file so that it can be directly opened for testing in futre.

### ISSUE THREAD

**Issue by mehulwarade** [thunderclient/thunder-client-support#1597]
**Please describe feature/problem details and the solution you'd like.**
The whole query to be stored as a file in a particular location so that when opened/ imported in thunder client, it can start off at the same place where we last left it.

**Describe alternatives you've considered**
Currently I have to copy the whole query and the request again and again. The headers and body and all other information needs to be copied too if I want to make a small change like changing from post to get.

The collection feature is good and helps a lot to organise but storing the request as a file will help easy management of the folders and easy to share across group of developers. Imagine a project with a set of premade thunder client config files that can help test different features of the project. 

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
No plans to support this.

we already have git sync feature
https://docs.thunderclient.com/team
