### ISSUE TITLE
Form Data import strips out =

### ISSUE THREAD

**Issue by IrishBruse** [thunderclient/thunder-client-support#1598]
**Describe the bug**
Form Data import strips out =

**To Reproduce**
foo=abc==&bar=123

foo abc
bar 123

**Expected behavior**
foo abc==
bar 123

**Platform:** 
 - OS: MacOS
 - vscode version: 1.91.1
 - node version: 20.9.0
 - extension version: 2.25.0

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
The bug is fixed in `v2.29.11`
