### ISSUE TITLE
Locking features behind paywall.

### ISSUE THREAD

**Issue by DarinClarkSE** [thunderclient/thunder-client-support#1599]
I am trying to get everyone to realize how great ThunderClient is and get our company to license it but you are killing me with locking Scripting behind a paywall. My efforts may be dead before they are even started. Please reconsider this latest move.

**Comment by rangav** [comment]
Hi @DarinClarkSE, thanks for the feedback.

Please share your company plans using below form
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
closing this issue, you can use the above contact form if you have any further questions
