### ISSUE TITLE
Using Tests for retry function

### ISSUE THREAD

**Issue by db-pw-rocker** [thunderclient/thunder-client-support#1600]
**Question:**
Hi,
we are testing a lot of asyncron services.. and for that we are using the "Retry Request" from your documentation...
https://docs.thunderclient.com/scripting/send-request

Is it possible to use the tests from "Tests section" within the Scripting area (with retry) as the indicator for an successful retry (loop condition)? 
Otherwise we would need to dublicate the tests in the "Scripting" area.. :/

An example would be nice.

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Thanks @db-pw-rocker for the feedback, Will review it.

**Comment by rangav** [comment]
We have implemented this feature in v2.25.5

Release Notes
https://github.com/thunderclient/thunder-client-support/releases/tag/v2.25.5
