### ISSUE TITLE
Update Feature Limit Table

### ISSUE THREAD

**Issue by noahlup** [thunderclient/thunder-client-support#1608]
With the recent update the Environment feature went to paid plans only.

Would be nice if that change would be reflected in the pricing information / compare plans section on the website, with Environments on the Free plan being crossed out.

**Comment by rangav** [comment]
Environments are still available in the free version. Only **Global Environment** is available in the paid version.

**Comment by noahlup** [comment]
Then This now changes to a bug report:
**Describe the bug**
Local Environment not available in free version

**To Reproduce**
Install latest Version of Thunderclient
Click to add new Local Environment
Get Error Message
![grafik](https://github.com/user-attachments/assets/65b2b3e1-60af-4be7-b3b8-b0cf3c482baf)


**Expected behavior**
Environment being set / existing Environment being usable

**Platform:** 
 - OS: Windows 10 / 11
 - vscode version: 1.92.1 / 1.93.1
 - node version: 20
 - extension version: v2.25.5

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
Local Env is also a global environment

**Comment by rangav** [comment]
Thanks for the feedback, Update the compare table
https://www.thunderclient.com/pricing

**Comment by noahlup** [comment]
Confusing naming, but ok.
Then I just have to copy all variables into a new Env.
imho the warning message is worded in a way easily misunderstood, might be sth to look into still
`The Global or Local Environment Feature is available only in the paid version.` reads as if Env is not supported at all
