### ISSUE TITLE
Data not available in Tests, Scripting

### ISSUE THREAD

**Issue by 3rdTimeCharm** [thunderclient/thunder-client-support#1609]
I am replacing the way we call custom scripts from our Tests.  I have included a simple project to demonstrate.  See the folder 'DataDriven_Add' to see I have referenced a JS file (deprecated, but it still works for now).
When I Run All for that folder and choose 'create.csv' for the Data, this test will pass:
`json|validateName({{firstname}},{{lastname}})  equal  true`

When I try to replace that functionality in the 'Scripting' tab, I cannot seem to reference the current value for firstname from the data file, seen on line 10 below.

![image](https://github.com/user-attachments/assets/4290deae-fd52-424e-81bb-5096cb575600)

Windows 11
vscode 1.93.1
TC version 2.25
paid version
[TC_DeprecatedCustomScripts.zip](https://github.com/user-attachments/files/17078894/TC_DeprecatedCustomScripts.zip)

**Comment by rangav** [comment]
You should use api to read variables in scripts `tc.getVar("firstname")`

**Comment by 3rdTimeCharm** [comment]
Thank you!  I didn't realize that would work - I believe the documentation says to "Get the value of an environment variable."  
I appreciate the quick response.
