### ISSUE TITLE
ERROR: The file-sending feature is available only in the paid version.

### ISSUE THREAD

**Issue by sao-coding** [thunderclient/thunder-client-support#1610]
**Question:**
ERROR: The file-sending feature is available only in the paid version.
**Are you using the free version/paid version/trial:**
Does this feature require payment now?
![image](https://github.com/user-attachments/assets/d6872fb5-1e53-455b-97ba-cb9f4911e1b2)

**Comment by rangav** [comment]
Yes, this a paid feature now.

**Comment by sherdooh** [comment]
Go POSTMAN
