### ISSUE TITLE
Enable global settings to set 'clear cookies' for each created request

### ISSUE THREAD

**Issue by AlekStyk** [thunderclient/thunder-client-support#1612]
**Please describe feature/problem details and the solution you'd like.**
Currently, I have to manually set 'clear cookies' to true for every newly created request. This is very problematic in projects where different authorization methods are tested. Now it is very easy to do a mistake and not setted that option to true.
One mistake = the entire collection runs incorrectly when using 'run all'.
Finding an rquest that doesn't have the 'clear cookies' option is also a pain, because the clearCookies field set to false is not saved in the collections json.

**Describe alternatives you've considered**
- Enable global settings to set 'clear cookies' for each created request
- Add in collections json an object 'preReq'  when clearCookies is set to false, example:
`"preReq": {
                "options": {
                    "clearCookies": false
                }
            }
        }`

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Hi @AlekStyk 

You can use scripting for this use case. Use below script in Collection settings -> Pre-Run -> Scripting

```js
await tc.clearCookies(tc.request.url);
```
https://docs.thunderclient.com/features/cookies#clear-cookies

2. If the `clearCookies` setting is not present in the JSON, it defaults to false.

**Comment by AlekStyk** [comment]
Okay, thank you i will try it. 
Will this also work for individual folders within the collection, If I want to "run all" for just one specific folder? Or do I need to paste this script into the settings of each folder as well?
I have many folders with thousands of requests that should have the "clear cookies" option enabled.

**Comment by rangav** [comment]
If you add script at collection level, it will work for all folders and requests in that collection

**Comment by rangav** [comment]
Closing this issue, feel free to continue discussion if you have any further questions

**Comment by rangav** [comment]
Forgot to mention, There is Clear Cookies option in Collection/Folder Settings UI.

<img width="1145" alt="Screenshot 2024-10-04 at 17 21 54" src="https://github.com/user-attachments/assets/4166d2a4-95cc-4a71-8d6d-cf28777fa399">

**Comment by AlekStyk** [comment]
Sorry but I dont thnik this script is working as I expect. 
I have a collection of requests, and I need the Clear Cookies option to be enabled for each of them, because I have cases where I need to check failed authorization.
I see that cookies are being saved in the Cookie Manager despite the script set in the settings.
![obraz](https://github.com/user-attachments/assets/64788ca6-57b8-411d-b78b-0a6862c693d5)
Because of this, my requests is returning a 200 status where I should be getting a 403, as I'm sending it without the cookie header.
![obraz](https://github.com/user-attachments/assets/c336cb1e-1390-41af-841b-8061988b812e)

**Comment by rangav** [comment]
I have tested the clear cookies and it is working for me, can please verify in the `Html Report`

<img width="1105" alt="Screenshot 2024-10-07 at 15 49 12" src="https://github.com/user-attachments/assets/53e8a73f-44a0-493e-85da-90c588ee9c79">
