### ISSUE TITLE
Header update via scripting not reflected in UI

### ISSUE THREAD

**Issue by aagranovExtend** [thunderclient/thunder-client-support#1613]
**Describe the bug**
The header UI only seems to update by manual input, not via scripting.

**To Reproduce**
What I do is in the Pre Run script, read an access token fro the OAuth2 tab and write it into a header via 

const accessToken = tc.request.auth.oauth2.accessToken
tc.request.setHeader('x-access-token', accessToken)

the actual request going out is correct, but the Headers UI still shows the old value.

**Expected behavior**
I'd expect the header value to be updated in the UI.

**Platform:** 
 - OS: macOS Sonoma
 - vscode version: 1.90.0
 - node version: 20
 - extension version: 2.25.8

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
@aagranovExtend The Authorization value is set at time of sending the request, which is after the pre-req script execution.

You can use the `Header Name` property for this use-case which is available from `v2.25.7`

<img width="740" alt="Screenshot 2024-09-26 at 04 37 46" src="https://github.com/user-attachments/assets/ebd54817-c7db-4118-9101-e781e735a6b2">

**Comment by rangav** [comment]
@aagranovExtend Are you still experiencing the issue, or has it been resolved?

**Comment by rangav** [comment]
Closing this issue, feel free to continue discussion if needed
