### ISSUE TITLE
How to use my upgraded plan in the vscode

### ISSUE THREAD

**Issue by pgle39** [thunderclient/thunder-client-support#1615]
**Question:**
i purchased your premium plan to use for testing socket.io inside vscode
how do i link my subscription to use websockets , i already have made the payment.

paid  version

**Comment by rangav** [comment]
Please add your email to Team Members tab in your account 

and then login from the extension 
https://docs.thunderclient.com/others/login

**Comment by rangav** [comment]
@pgle39 Was the issue resolved for you?

**Comment by rangav** [comment]
closing this issue
