### ISSUE TITLE
Collection requests don't run in a defined order

### ISSUE THREAD

**Issue by AlekStyk** [thunderclient/thunder-client-support#1616]
**Describe the bug**
The issue with requests mixing up is back. The problem I report [here](https://github.com/thunderclient/thunder-client-support/issues/1425l) is occurring again, but in a different scenario.
The problem is with sorting requests in a folder. Upon verifying the sortNum in the JSON file, it is noticeable that values are being incorrectly assigned. 
The most often occurs when I duplicate a request that has an older date

**To Reproduce**
I have a colletion where requests were added a long time ago. I duplicate the requests and then verify the order of the requests in 'Run all'.

![obraz](https://github.com/user-attachments/assets/84bc191d-16d0-4092-921d-80d6daa7ae0f)

They were assigned this sort number
![obraz](https://github.com/user-attachments/assets/a49c79dd-a06f-4c5c-8fc5-3e9d4c325d83)

When I close and reopen the project, these requests are in different places than where I have set them.
![obraz](https://github.com/user-attachments/assets/8e156c04-6146-498d-8931-205f5c96a74d)

**Expected behavior**
Order of requests defined in a collections folder is the same as order of requests after Run all. My colleagues also reporting this issue when they want to fix the old tests.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.90.2 (user setup)
 - node version: Node.js: 20.9.0
 - extension version: v2.25.8

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
@AlekStyk 

Can you please follow below steps

1. Please run this command
<img width="631" alt="Screenshot 2024-09-27 at 13 35 36" src="https://github.com/user-attachments/assets/d33fcbf5-d58b-4e12-912b-a4b6752a2965">

2. Reload Vs Code
3. Rearrage any requests to your desired order
4. Reload VS Code and verify it.

**Comment by AlekStyk** [comment]
Okay, thank you, for now it helps.
So, should I use it every time when I see the requests getting mixed up?
