### ISSUE TITLE
ZIP response not free anymore starting with version 2.25.9?

### ISSUE THREAD

**Issue by metawops** [thunderclient/thunder-client-support#1617]
I'm using the free version and up to v2.25.8 I was able to get responses to requests that answer with a ZIP file. As usual I get the choice to save the response via a "Save File" button incase of my request that delivers a ca. 18 MB ZIP response:

![image](https://github.com/user-attachments/assets/0b267a7b-1d67-43b5-afb8-df193d17a585)

I was shocked to learn that with the latest update to v2.25.9 this now seems to be a paid feature. Making the same request in 2.25.9 I get this now:

![image](https://github.com/user-attachments/assets/68575a1f-d870-4c65-a527-7c18a09c6bc5)

Really? Why?

**Comment by rangav** [comment]
@metawops can you please share your company name?

**Comment by metawops** [comment]
I‘m using Thunder Client as a private hobbyist.

**Comment by rangav** [comment]
Thank you for the confirmation.

We initially made many features available in the free version with the expectation that companies would purchase a few licenses for their employees. However, in reality, thousands of employees have been using our software for commercial purposes without purchasing even a single license. To address this, we have decided to move some of these features to the paid version to encourage companies to obtain proper licenses.

In the coming months, our primary focus will be on growing our paid user base, which is crucial for ensuring the long-term sustainability and continued development of our software. We are committed to providing value to our paying customers while discouraging misuse of the free version.

**Comment by metawops** [comment]
Thx. Time to look for a new & truly FOSS tool. Goodbye Thunder Client. 👋 It was super cool when it was new. 🤷‍♂️
