### ISSUE TITLE
Cookie header error 

### ISSUE THREAD

**Issue by Band-Aid** [thunderclient/thunder-client-support#1618]
**Describe the bug**
I am getting the following error even though I have configured the Cookie header param.
Error when sending request: First argument to setCookie must be a Cookie object or string

**To Reproduce**
1. Create a new request
2. enter any URL
3. In the header type in Cookie: seesion.jwt=xxxxx
4. Notice the error
Error when sending request: First argument to setCookie must be a Cookie object or string
![image](https://github.com/user-attachments/assets/145ea7c6-3674-44de-a836-599fe382a857)

removing the dot in the cookie param does not prompt you with the error
It appears as though the app does not like the dot in between. This previously worked with out any issues.
Something must have changed in how you parse the cookie params

**Expected behavior**

**Platform:** 
 - OS: Windows 11 (ARM / MacOS ARM
 - vscode version: 1.91.1
 - node version: 20 LTS
 - extension version: 2.27.0

**Are you using the free version/paid version/trial:**
Paid version

**Comment by esp0314** [comment]
We experienced this too using V2.27.0. @rangav, for now we downgraded to v2.26.1
![image](https://github.com/user-attachments/assets/61539dfc-e47f-4c90-8ae8-4ea7007a1c54)

![image](https://github.com/user-attachments/assets/4dba52d7-e2c4-4bb9-8e95-a715fd039a33)

**Comment by rangav** [comment]
Thanks for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is fixed in `v2.27.3`
Please test it and let me know your feedback.

**Comment by esp0314** [comment]
Verified working, thank you @rangav 
![image](https://github.com/user-attachments/assets/6392c37d-4efe-437e-87cf-76d6ab6e0b49)

![image](https://github.com/user-attachments/assets/c2fe89b4-5223-410a-9a86-0dde49f82768)
