### ISSUE TITLE
Inquiry Regarding the Usage and Generation of the _id in Thunderclient Json Files

### ISSUE THREAD

**Issue by esp0314** [thunderclient/thunder-client-support#1619]
**Question:**

@rangav,

I have a question regarding the _id. Could you please explain how the _id is generated? Additionally, when I reviewed all files generated by Thunderclient, I did not find any references to how this _id is used. I noticed that removing this field causes the API request to fail, so I understand that it holds some significance. Could you provide more information about the role of this field and why it is required for successful API requests?
![image](https://github.com/user-attachments/assets/98c7dd80-2490-4bcd-b783-b0c12cede43a)

**Are you using the free version/paid version/trial:** - Paid version

**Comment by rangav** [comment]
@esp0314 It's similar to database row ID.
