### ISSUE TITLE
Activity Tab only shows the last request per API

### ISSUE THREAD

**Issue by kaye-alvarado** [thunderclient/thunder-client-support#1620]
**Please describe feature/problem details and the solution you'd like.**
Activity tab doesn't track each request trigger. If a request is triggered once, then headers are updated and triggered again, it doesn't track the other request as a separate activity.

**Describe alternatives you've considered**
none

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
@kaye-alvarado this is by design. We only track changes when the URL or method is modified.
