### ISSUE TITLE
Asking me to pay for the functionality import from cURL, it might be a bug

### ISSUE THREAD

**Issue by AmauryDanisCousandier** [thunderclient/thunder-client-support#1621]
**Describe the bug**

Asking to pay
**To Reproduce**

three dots menu near text bar, then click import cURL
**Expected behavior**

to let me paste the cURL request
**Platform:** 
 - OS: win11
 - vscode version: 1.94.0
 - node version: 20.10.0
 - extension version: v2.27.6

**Are you using the free version/paid version/trial:**
regular version

**Comment by TheRealSmeddy** [comment]
This is not a bug, looks like he just included that feature into paid version...
![image](https://github.com/user-attachments/assets/b9b41d4e-1485-42fa-8914-95b4c303132d)

**Comment by rangav** [comment]
This is a paid feature now.
