### ISSUE TITLE
Characters inserted at wrong location when editing JSON body

### ISSUE THREAD

**Issue by Garrett-Wolfe** [thunderclient/thunder-client-support#1622]
**Describe the bug**
When editing the JSON body of a request, new characters are not actually inserted where the cursor appears visually.

**Example**
![cursor_error](https://github.com/user-attachments/assets/0e83b884-b07e-4d68-b731-5d1fccd3b0d4)

**To Reproduce**
1. Open a new request 
2. Navigate to Body tab and then select JSON
3. Start typing

**Expected behavior**
Characters should be inserted where the cursor is

**Platform:** 
 - OS: Ubuntu 24.04.1 LTS
 - vscode version: 1.93.1
 - node version: 20.15.1
 - extension version: v2.27.6

**Detailed VS Code Info**
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-45-generic

**Are you using the free version/paid version/trial:**
Free Version

**Comment by rangav** [comment]
@Garrett-Wolfe please search for existing issues for solution.

**Comment by Garrett-Wolfe** [comment]
I did search for existing issues. If you're thinking about these, they are not the same issue:
#1499
#1563
#423

**Comment by rangav** [comment]
Its a custom font issue, please go though the solutions above and try it

https://github.com/thunderclient/thunder-client-support/issues/1326#issuecomment-1714123998

**Comment by Garrett-Wolfe** [comment]
Oh I see. I didn't think to look through closed issues. Thanks
