### ISSUE TITLE
Disable auto-save

### ISSUE THREAD

**Issue by Band-Aid** [thunderclient/thunder-client-support#1623]
**Question:**
Hi! How do you disable Thunder Client from automatically saving edits made to requests? I’m using a template API, and every time I make changes and run the request, it saves over the original template.

How can I set it so that it only saves when I hit the save button?

**Are you using the free version/paid version/trial:**
Paid

**Comment by rangav** [comment]
Please disable setting `Save Request on Send` in the settings view.

**Comment by Band-Aid** [comment]
Thank you! You made my day!

**Comment by rangav** [comment]
You are welcome :)

We would appreciate it if you could share your Thunder Client experience by writing a review on the Marketplace
https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client
