### ISSUE TITLE
Unable to Input Chinese in URL and Query Params Fields on macOS in Thunder Client

### ISSUE THREAD

**Issue by iknki** [thunderclient/thunder-client-support#1624]
Description: I'm experiencing an issue with the Thunder Client extension on my Mac (macOS 12.7.6). In both the URL and Query Params input fields, I'm unable to input Chinese characters, even though this works perfectly fine on my Windows system with the same version of Thunder Client. It appears that the issue is specific to macOS.

Additionally, I encountered a similar issue as mentioned in [issue #535](https://github.com/thunderclient/thunder-client-support/issues/535) (which concerns Ubuntu), but in my case, I'm using macOS, and the issue does not occur on Windows.

Expected Behavior: Chinese characters should be input correctly in both the URL and Query Params fields, as it works on Windows.

Actual Behavior: Chinese characters are not input or recognized in both the URL and Query Params fields.

System Info:

macOS Version: 12.7.6
Visual Studio Code Version: 1.94.2
Thunder Client Version: 2.28.0
Additional Context: Copying and pasting Chinese characters into the URL and Query Params fields works correctly. However, the issue arises when trying to input Chinese directly using the macOS built-in input method. The characters do not appear in the input fields as expected.

**Comment by rangav** [comment]
closing issue, please fill in the complete issue template details
