### ISSUE TITLE
ioutil is deprecated since Go 1.16

### ISSUE THREAD

**Issue by kebyn** [thunderclient/thunder-client-support#1626]
**Describe the bug**

[ioutil](https://pkg.go.dev/io/ioutil) is deprecated since Go 1.16
For example, `ioutil.ReadAll` this function simply calls `io.ReadAll`

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - node version:
 - extension version:

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
We don't use go

**Comment by kebyn** [comment]
The automatically generated golang code snippet has this problem

<img width="676" alt="image" src="https://github.com/user-attachments/assets/9ea72280-d73d-41fd-ac4c-d8329c266f63">

**Comment by rangav** [comment]
Ok got it.

The codegen is powered by this library, please report to them.
https://github.com/Kong/httpsnippet

**Comment by kebyn** [comment]
They fixed this issue a long time ago.

https://github.com/Kong/httpsnippet/pull/305

**Comment by rangav** [comment]
Thanks for the confirmation, will update the package version

**Comment by rangav** [comment]
The library is updated and the new version is published to the marketplace. Please update to `v2.29.5.`

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.29.5

Please test it and let me know your feedback
