### ISSUE TITLE
Large data set not allowed when running collection

### ISSUE THREAD

**Issue by 3rdTimeCharm** [thunderclient/thunder-client-support#1629]
I have a folder with a request that adds response data to a (csv) file.
I use that file when running 2 other collections.
When the data file contains 125 lines of data or less, it works.  If the data file for Run Collection contains 250 lines, it fails with this error:
`Error while parsing csv file - Too many fields: expected 4 fields but parsed 751 `

I'm forced to chop up my data file (we have 500 lines of data, total file size is only 40kB) into 5 files.

 - OS: Win 10
 - vscode version: 1.94.2
 - extension version: 2.29.2

**paid version**

**Comment by rangav** [comment]
Can you verify the large csv is correctly formatted using any tool?

**Comment by 3rdTimeCharm** [comment]
I tried CSVLint.io online and Excel locally.

**Comment by rangav** [comment]
Is it possible to email the sample CSV file that is not working, So we can investigate the issue?

**Comment by 3rdTimeCharm** [comment]
Unfortunately I don't have the original anymore.  We do plan on doing this again next week, if the error recurs - I will attach the file here.  Thank you for looking into this issue.
I take it that there should not be a limit to the size of data files used as input to run a Collection.

**Comment by rangav** [comment]
No there is no limit file size. I will test with a large CSV and verify if there are any issues.

**Comment by 3rdTimeCharm** [comment]
We have just returned to this effort today and had the opportunity to create and use new .csv files with up to 1000 lines per file.  We encountered no problems, so all I can guess was that there was a bad character in that initial file and when I split it, the character wasn't copied over.
Thanks for looking into this issue..
