### ISSUE TITLE
"OS keyring couldn't be identified" despite having KDE Wallet

### ISSUE THREAD

**Issue by seyfu-t** [thunderclient/thunder-client-support#1631]
**Question:** When I launch thunder client, i get a pop-up telling me that no OS keyring could be identified despite the fact that I have KDE Wallet running and other application are able to make use of it. Am I missing something? Or is VSCode/VSCodium incapable of using it? (screenshot below)

I'm running Hyprland under Archlinux and I use VSCodium

**Are you using the free version/paid version/trial:** free

![grafik](https://github.com/user-attachments/assets/750b9b3e-d7f2-4aaa-bcbd-84eed10695ea)

**Comment by rangav** [comment]
This is not related to Thunder Client. Related to vscode.

https://github.com/microsoft/vscode/issues/187842#issuecomment-1634523221
