### ISSUE TITLE
Bug and Feature and Question ;)

### ISSUE THREAD

**Issue by db-pw-rocker** [thunderclient/thunder-client-support#1633]
**Question:**
Hi guys,
we want to integrate ThunderClient with CLI and do a reporting to Jira Xray as the Testmanagementtool.
Therefore we want to use the xray API and using the junit xml report from thunderclient.
https://docs.getxray.app/pages/viewpage.action?pageId=46886185#ImportExecutionResultsREST-JUnitXMLresults

But:
We want to have a good mapping, like the thunderclient html report.
We want to have a collection as a testcase and the "Tests from ThunderClient - like check 202" should be a teststep.

Then we would have a nice report and mapping in xray.

And I think a collection ist more a "Testcase" then 1 request test ;)

**Are you using the free version/paid version/trial:**
paid with a lot of licenses in Deutsche Bahn in Germany :)

**Comment by db-pw-rocker** [comment]
![Screenshot 2024-10-29 094638](https://github.com/user-attachments/assets/184d4500-7043-443f-a6e9-6cad49b54050)

but junit report looks like:
  <testsuite name="Send routing request TK - RM" id="26693975-1948-4a6a-bad5-b20010b4b2ef" tests="3" failures="0" assertions="3" time="0.030" timestamp="2024-10-25T18:24:53.700Z">
    <property name="url" value="https://helloWorld"/>
    <property name="method" value="post"/>
    <testcase name="Response Code equal to 202" classname="Kapafinder_ServiceTests.SendroutingrequestTK-RM" assertions="1"/>
    <testcase name="Response Time &lt; 500" classname="Kapafinder_ServiceTests.SendroutingrequestTK-RM" assertions="1"/>
    <testcase name="Response Body is JSON true" classname="Kapafinder_ServiceTests.SendroutingrequestTK-RM" assertions="1"/>
  </testsuite>


it would be great to have an option like "xray_report" to do a more useful mapping.

**Comment by rangav** [comment]
@db-pw-rocker thanks for the feedback. Will add to roadmap

**Comment by db-pw-rocker** [comment]
thanks for the quick response, this "feature" is quite important for us as we have multiple teams and projects with thunderclient and we need the full view of unit / service / end2end tests (with different tools)
let me know once you **have a specific release date** (and questions ;))

**Comment by db-pw-rocker** [comment]
junit report:  
<testsuite name="Send routing request TK - RM" id="26693975-1948-4a6a-bad5-b20010b4b2ef" tests="3" failures="0" assertions="3" time="0.030" timestamp="2024-10-25T18:24:53.700Z">
    <property name="url" value="https://>
    <property name="method" value="post"/>
    <testcase name="Response Code equal to 202" classname="Kapafinder_ServiceTests.SendroutingrequestTK-RM" assertions="1"/>
    <testcase name="Response Time &lt; 500" classname="Kapafinder_ServiceTests.SendroutingrequestTK-RM" assertions="1"/>
    <testcase name="Response Body is JSON true" classname="Kapafinder_ServiceTests.SendroutingrequestTK-RM" assertions="1"/>
  </testsuite>

**Comment by db-pw-rocker** [comment]
![image](https://github.com/user-attachments/assets/889ec0d9-3c65-4e20-8c4d-03882e808553)

**Comment by rangav** [comment]
can you please share the current XML format sample and the desired XML format sample, so it will be useful to improve it?

**Comment by db-pw-rocker** [comment]
current is added.

the desired xml can be found in xray documentation
https://docs.getxray.app/display/XRAY/Taking+advantage+of+JUnit+XML+reports

![image](https://github.com/user-attachments/assets/c84d1169-be8b-4615-b1ed-1bd52ce2a1d2)

**Comment by rangav** [comment]
Thanks for sharing. I will look into it ASAP.

**Comment by rangav** [comment]
Hi @db-pw-rocker,

I'm not clear on what changes you need in the current XML.

Could you schedule a call on Monday to help me better understand your requirements?

Please reply with your availability using the form below:
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
Implemented in CLI version v1.19.0
https://github.com/thunderclient/thunder-client-support/releases/tag/v2.29.10
