### ISSUE TITLE
form-encoded body gets truncated to 25 characters

### ISSUE THREAD

**Issue by TarekSalha** [thunderclient/thunder-client-support#1634]
**Describe the bug**
when using form-encoded body long arguments get truncated to 25 characters. This leads to failing requests as not the full arguments are delivered to the api server. When I export the same failing request to python using the code snippet and execute it separately from thunderclient it works like a charm.

Apart from this, the logs suggest, that the correct request has been sent, which is confusing.

**To Reproduce**
I encountered the problem when asking Azure AD for a token. When using 26 characters, the last one is truncated from the string
![image](https://github.com/user-attachments/assets/e596d89f-5add-45f4-b8e4-9a97a531caf7)

these are the logs from thunderclients output, that suggest, that also z was sent at the end of the string:
```
---------------- Running Request: ----------------
Request Url: https://login.microsoftonline.com/XXXXXXXX/oauth2/v2.0/token
Method: POST
Request Headers:
{
  "cookie": "XXXXX",
  "Accept": "application/json",
  "User-Agent": "Thunder Client (https://www.thunderclient.com)",
  "Accept-Encoding": "gzip, deflate",
  "Connection": "keep-alive",
  "Content-Type": "application/x-www-form-urlencoded",
  "Content-Length": "175"
}
Request Body:
{
  "grant_type": "client_credentials",
  "client_secret": "XXXXXXXX",
  "scope": "XXXXXXXXX",
  "client_id": "abcdefghijklmnopqrstuvxyz"
}
```
**Expected behavior**
as described above, the very same request works when exported to python (of course with a REAL client_id, not the alphabet ;-)). My expectation is, that it should transmit ALL characters.

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.94.2
 - node version: 22.6.0
 - extension version: 2.29.3

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
its working for me, you can test with - https://httpbin.org/anything

<img width="1051" alt="Screenshot 2024-11-01 at 10 00 06" src="https://github.com/user-attachments/assets/e58f72c5-e39d-46e9-98c9-0aa577f93240">

**Comment by rangav** [comment]
closing the issue due to inactivity.
