### ISSUE TITLE
Redo not working when editing query parameters

### ISSUE THREAD

**Issue by moltob** [thunderclient/thunder-client-support#1636]
**Describe the bug**
When editing a request's query parameter's value, the redo hotkey (ctrl-y) is not working but instead performs an undo.

**To Reproduce**
1. Open query parameters view of a request.
2. Add a new query parameter
3. Type some text into the value field
4. Hit "CTRL-Z" once or twice to undo (works)
5. Hit "CTRL-Y" a few times to redo (does not work, but still does undo)

**Expected behavior**
CTRL-Y performs a redo operation.

**Platform:** 
 - OS: Windows (WSL), *German keyboard layout*
 - vscode version: 1.95.1
 - node version: 21.7.3
 - extension version: 2.29.6

**Are you using the free version/paid version/trial:**
Paid.

**Comment by moltob** [comment]
Done

**Comment by rangav** [comment]
Thanks for the confirmation. I wiill verify and fix it asap.

**Comment by rangav** [comment]
undo keyboard shortcut is `ctrl + Shft + Z`

**Comment by moltob** [comment]
Is that just a comment or the supposed solution?

The "redo" shortcut in most applications is CTRL-Y. The mentioned CTRL-SHIFT-Z is an alternative sometimes found in applications (I read Photoshop). Windows therefore binds _both_ shortcuts to "redo" automatically.

Regardless of that, _my_ VSCode shortcuts choose to take over the system settings, meaning CTRL-Y is still an active "redo" shortcut:

![image](https://github.com/user-attachments/assets/4615f1a2-2ed7-4e88-9237-da50ad4ce877)

Why would an extension choose to change that? And in fact make it even worse and bind "undo" to CTRL-Y as well?

**Comment by rangav** [comment]
We did not change anything to keybindings

We implemented standard keybindings for undo and redo

See vscode keyboard shortcuts
<img width="357" alt="Screenshot 2024-11-10 at 11 38 27" src="https://github.com/user-attachments/assets/5827be0e-6a32-4344-a7d9-81b8072d522c">

**Comment by moltob** [comment]
It is not up to the extension to decide on bindings:

![image](https://github.com/user-attachments/assets/4871edf4-6b92-43d4-a4f3-61aed10f3e93)

**Comment by rangav** [comment]
Did you change to keybindings for `redo`?

**Comment by moltob** [comment]
No, as I wrote above, this is Windows default.

**Comment by rangav** [comment]
Thanks for the clarification, I will look into the issue.

**Comment by rangav** [comment]
This bug is fixed in `v2.32.9`, Please test it and let me know your feedback.

https://github.com/thunderclient/thunder-client-support/releases/tag/v2.32.9
