### ISSUE TITLE
Proposal: Implement a collection not using monolithic approach.

### ISSUE THREAD

**Issue by aagranovExtend** [thunderclient/thunder-client-support#1637]
**Please describe feature/problem details and the solution you'd like.**
The issue right now is shared thunder client collections under source control are impossible to manager via the standard Git diff approach, since it's 1 JSON file that keeps getting bigger.

**Describe alternatives you've considered**
An alternative is a hierarchical file 'system' where a collection contains references to folders and each request is its own JSON file. Under folders, each request would be a JSON file reference. That way when modifying/adding new requests and performing Git diff, it becomes feasible to see what the changes are and not have teammates possibly overwriting each others changes.

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
We have implemented alternative solution one file per request to address this issue.

see details here
https://github.com/thunderclient/thunder-client-support/releases/tag/v2.23.0

**Comment by aagranovExtend** [comment]
Thanks!
