### ISSUE TITLE
SSE not showing any output

### ISSUE THREAD

**Issue by jasonkochel** [thunderclient/thunder-client-support#1642]
**Describe the bug**
When I connect to an endpoint using server-sent events, nothing shows in the Response tab.  Nothing shows during the streaming, and even after the entire call is complete (and it shows a 200 status), the Response tab is empty.  Testing the same endpoint in Chrome works as expected.

**To Reproduce**
Make a connection to https://sse.dev/test

**Expected behavior**
Messages to be shown as they are received

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.95.3
 - node version: 21.2.0
 - extension version: 2.29.12

**Are you using the free version/paid version/trial:**
Paid (I just subscribed to the paid version specifically to use SSE)

**Comment by jasonkochel** [comment]
I ended up getting this to work, but there are some confusing bits that may help others or be improved.

I was creating the request as part of a collection.  "New Request" on the collection context menu does not give an option for "Event Stream Request".  I had set it up as a normal GET request, and the button did show "Connect" instead of "Send", so it appeared to be doing the same thing as an actual "Event Stream Request", but just not showing any output.

I see now that you have to do "New Request -> Event Stream Request" from the top button.  This puts it in the "Activity" tab but I don't see any way to add it to a collection.

**Comment by rangav** [comment]
Hi @jasonkochel Thanks for the feedback. I will add the option to save SSE to collection in the next update.

**Comment by rangav** [comment]
Related #1522

**Comment by rangav** [comment]
`Save to collection` option enabled for SSE and WS requests in `v2.32.0`

Please update and let me know if any feedback.

**Comment by jasonkochel** [comment]
Works great, thanks!
