### ISSUE TITLE
20 Nov update

### ISSUE THREAD

**Issue by 7JUMPER7** [thunderclient/thunder-client-support#1644]
Thank you very much, now I can't access my stored endpoint which I store BEFORE updated.
Very cool update!
Never seen such an aggressive thirst for money...

**Comment by 7JUMPER7** [comment]
> Have you read the recent announcement? https://github.com/thunderclient/thunder-client-support/releases/tag/v2.29.0
> 
> Please update to the latest version **v2.30.0**, you can access your data
> 
> If you would like to export data https://docs.thunderclient.com/features/import#export-data

I have updated and still can't access any endpoint because ONE of my collections has more that 15 endpoints.
Only way is to export to file.
Now I'm going to fuck with it and search any alternative, because I'm not gonna give you money after such a move, especially in the form of a MONTHLY subscription for fricking VSCode extension.

**Comment by rangav** [comment]
You can export data and use any other tool that suits your needs.
