### ISSUE TITLE
no where to export my data

### ISSUE THREAD

**Issue by luoyetx** [thunderclient/thunder-client-support#1646]
**Question:**

for free version, i can not access my request data today suddenly, and from document, it says we can export data from collections, and i can not create new collections as i use the extension in remote mode. Now i can not access my request anymore, if i downgrade the version, i can not even see the request list.

**Are you using the free version/paid version/trial:**
<img width="372" alt="image" src="https://github.com/user-attachments/assets/9e11f4f2-2623-4c0d-a42e-ce5448a094bf">

**Comment by rangav** [comment]
update extension to latest version 

Your data location 
https://docs.thunderclient.com/#storage-location

Export data
https://docs.thunderclient.com/features/import#export-data
