### ISSUE TITLE
You must be joking 

### ISSUE THREAD

**Issue by devhindo** [thunderclient/thunder-client-support#1647]
lol I can't use it on wsl anymore. It's just my local development environment doing some hobby projects
![image](https://github.com/user-attachments/assets/fdcf4460-c026-4709-9892-73369adebcf8)

**Comment by rangav** [comment]
Yes, its a paid feature now.

Read announcement 
https://github.com/thunderclient/thunder-client-support/releases/tag/v2.29.0
