### ISSUE TITLE
Store active environment outside of version controlled files when saving Thunder Client data to workspace

### ISSUE THREAD

**Issue by ryanmcfall** [thunderclient/thunder-client-support#1655]
**Please describe feature/problem details and the solution you'd like.**

I have the "Save To Workspace" option turned on.  When I use multiple environments, the JSON files for those environments contains a boolean "default" property.  Switching between environments toggles that property on/off in my various environment files, requiring me to either revert the change or commit it to version control.

It should be possible for the developers on a team to have different default profiles active and avoid changes to version controlled files when switching.

**Describe alternatives you've considered**

I don't have any great ideas on how to get around this, other than not staging the hunk of the environment files with this information in it.  But this is very brittle, and also leaves my working directory in a constant dirty state.

**Are you using the free version/paid version/trial:**
Paid

**Comment by rangav** [comment]
Hi @ryanmcfall 

We already have this feature, please see below link for solution 
https://github.com/thunderclient/thunder-client-support/issues/1250#issuecomment-1956787154

**Comment by ryanmcfall** [comment]
Thank you!  

It seems the setting of storing that value in local memory rather than in shared files should be the default.  I agree with the creator of #1250 when they said "I can't think of any use-cases where a user would want the change of the Active Environment committed to Git."

**Comment by rangav** [comment]
We have included the setting details in the docs

https://docs.thunderclient.com/features/environments/active-env#store-changes-in-memory
