### ISSUE TITLE
history release below 2.26.0 is missing on open-vsx.org

### ISSUE THREAD

**Issue by garylavayou** [thunderclient/thunder-client-support#1657]
**Describe the bug**

History release of thunder-client below 2.26.0 is missing on open-vsx.org.
I cannot find the history version 2.20.3, that I used in building a container image where the extension will be installed with vs code 1.80.
Previously, I downloaded the extension installation file to my local machine.
But now, I cannot find it on open-vsx.org.

**To Reproduce**

1. visit open-vsx.org.
2. search thunder-client and open the extension page.
3. click the version select box in the right column of the page, and scroll down to the bottom.

**Expected behavior**

I should see all the history releases in the select box.

**Are you using the free version/paid version/trial:**

free version.

---

This issue is not related to the extension is self, but might matter to the extension publishing procedure or extension release storage policy on open-vsx.org. But as a normal user, I cannot figure out what's wrong with it.

**Comment by rangav** [comment]
We don't support older versions anymore. Please update VS Code to v1.85 or above and update extension to latest version
