### ISSUE TITLE
Error - Cannot read properties of undefined (reading 'getCookies')

### ISSUE THREAD

**Issue by AlekStyk** [thunderclient/thunder-client-support#1659]
**Describe the bug**
Please, I have a problem, can you tell me what is wrong or can you fix it?
Each time I submit any request, I receive an error.
`Error when sending request: Cannot read properties of undefined (reading 'setCookie')`
or
`Error in Pre Request Script: - Cannot read properties of undefined (reading 'getCookies')`

I am only using pre run script in scripting on the collection:
`await tc.clearCookies(tc.request.url);`
but even if I remove that script, the error appear again.

I cant even open a Cookie manager.
I didn't change anything in the settings or in the repository, and it worked recently.

**To Reproduce**
I am sending any request POST/GET/PUT with different tests and settings.
On collection I have pre run script `await tc.clearCookies(tc.request.url);`
On every requests I have option 'ClearCookie' on.

There is Error in every request:
![Screenshot_1](https://github.com/user-attachments/assets/c148091f-6535-461f-ae35-3fbe5d6512fc)
![Screenshot_2](https://github.com/user-attachments/assets/3df7e2d9-afb6-4be8-bc45-5d672931f1df)

**Expected behavior**
Requests run without an error.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.90.2 (user setup)
 - node version: 20.9.0
 - extension version: v2.32.9

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
@AlekStyk can you please test with v2.31.0 and let me know if you have the same issue?

**Comment by rangav** [comment]
Thanks for confirmation, will verify and get back to you.

**Comment by rangav** [comment]
[vscode-thunder-client-2.32.10.vsix.zip](https://github.com/user-attachments/files/18078854/vscode-thunder-client-2.32.10.vsix.zip)

Can you please test using above VSIX file and let me know feedback.

**Comment by AlekStyk** [comment]
I did it, I restarted TC and VSC unfortunately error still appears.
![Screenshot_4](https://github.com/user-attachments/assets/8eb027fd-1061-4cfd-aed9-e9dcc864c20e)

 Also the Cookie Manager doesnt show anything
![obraz](https://github.com/user-attachments/assets/f85b9b3c-0c9b-41b2-a25e-d0a9801a2484)

**Comment by rangav** [comment]
Could you update VS Code to version 1.91.0 and try again?

Does this issue also occur for your colleagues?

**Comment by AlekStyk** [comment]
I update VSC version to June 2024 (version 1.91) but the problem still occured - cookie manager dont open and error appears. My colleagues has vscode version: 1.90.2 and lower TC version and for them it works, I tried that change but in my device the problem is still here. Maybe i deleted something from settings by accident? or did I changed something in folders? I dont know, please help

**Comment by rangav** [comment]
try these steps

- Uninstall the extension
- Reboot your windows
- Install the extension
- Test now

**Comment by AlekStyk** [comment]
I uninstalled the extension and even the VSC, then i rebooted windows and installed everything. The error still appear...
![obraz](https://github.com/user-attachments/assets/62c7fcec-ff89-452d-99c3-39a41963bfa3)

And the Cookie Manager doesnt work.

**Comment by AlekStyk** [comment]
This is happening on my work device, I need to check if I will be able to make such a call.

But I have more information.
From my analysis, it turns out that the Cookie manager is the main cause here. Its incorrect operation disrupts the work of requests. When I send requests without cookies in headers, everything is correct and I receive a response from the application, if I only use the option associated with Cookies, Error is thrown.

Cookie manager - doesnt work:
![obraz](https://github.com/user-attachments/assets/52ae9d0f-f1a7-46fe-891e-bd08aa9b94eb)

Request with Cookie in header and pre run Clear Cookies - doesnt work:
![obraz](https://github.com/user-attachments/assets/7eedf0da-77ea-4f0a-84c8-f7736ec40f3d)

Request without a cookie in header but with pre run clear cookies - doesnt work:
![obraz](https://github.com/user-attachments/assets/6c8c4988-e4be-4902-85b7-b20c658ee60a)

Request without a cookie in header and without pre run clear cookies - **works**:
![obraz](https://github.com/user-attachments/assets/be439cf5-0374-4267-b633-736f6cf98971)

I tried everything even the deletion of folder AppData\Roaming\Code and all of the \.vscode\extensions

**Comment by AlekStyk** [comment]
That doesn't work either, the error still appear. Do you think only reinstallation of my OS will work? Or do you know of any other solution I can try?
I can upgrade my Windows to 11 version if that will help, but I dont know what to do more :(

**Comment by ArturMarekNowak** [comment]
@rangav after our thorough investigation with @AlekStyk I would have a suggestion. I am not entirely sure if its possible or feasible but probably it would be a good idea to delete `%userprofile%\.th-client` folder whenever the tc is unistalled

**Comment by rangav** [comment]
Thanks @AlekStyk and @ArturMarekNowak for sharing the steps to fix this issue.

@ArturMarekNowak Thanks for the feedback. We will review your suggested solution.

**Comment by rangav** [comment]
We updated the extension in `v2.33.0` to catch cookie-related errors and display them in the logs. This will make it easier to identify similar errors if they occur in the future.

View Logs:
https://docs.thunderclient.com/features/logs
