### ISSUE TITLE
Unable to use thunderclient in Dev Container environment after upgrading

### ISSUE THREAD

**Issue by yoonustehrani** [thunderclient/thunder-client-support#1661]
**Describe the bug**

Recently it seems impossible to use thunderclient in dev container environment. this error is raised when clicking on the "new request" button in the sidebar.

**To Reproduce**

Once the "New Request" button in thunderclient sidebar is clicked, there's a toast error message on the right bottom side of the window declaring "Warning: The free version does not support use in VScode web, remote, or WSL". this is not so when using the extension in normal mode.
![Screenshot from 2024-12-14 13-06-19](https://github.com/user-attachments/assets/3e5eabc0-c02e-473f-8fab-be625afe61c1)

**Expected behavior**

I used to be able to utilize the extension in devcontainer mode of VSCode yet this behavior is happening after the last version upgrade.

**Platform:** 
 - OS: 22.04.1-Ubuntu
 - vscode version: 1.95.3
 - node version:
 - extension version: 2.32.9

**Are you using the free version/paid version/trial:**
I'm using the free version

**Comment by rangav** [comment]
@yoonustehrani Use in dev containers is not supported in the free version.

You need to upgrade to paid version.

**Comment by yoonustehrani** [comment]
> @yoonustehrani Use in dev containers is not supported in the free version.
> 
> You need to upgrade to paid version.

Is this a new policy ? because it was not used to be like this.

**Comment by rangav** [comment]
Yes

https://github.com/thunderclient/thunder-client-support/discussions/1648
