### ISSUE TITLE
Increase scrollbar width

### ISSUE THREAD

**Issue by Martini002** [thunderclient/thunder-client-support#622]
It is almost impossible to scroll down the list using the scrollbar drag and drop way.
Would be nice if the width of the bar could be increased.

Thank you

![image](https://user-images.githubusercontent.com/22435591/173604650-d120c0a3-79a6-4590-8f0c-2fd2c2d53966.png)

**Comment by rangav** [comment]
Thanks @Martini002 for the feedback

**Comment by jimith-plutus** [comment]
Any update for this?

**Comment by rangav** [comment]
Will provide setting to control width of the scroll bar in the next update.
