### ISSUE TITLE
Download file need a default path.

### ISSUE THREAD

**Issue by GreatAuk** [thunderclient/thunder-client-support#696]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Download file need a default path. such as Mac: /Users/***/Downloads

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @GreatAuk thanks for the feedback

VS Code api does not seem to this option, it's a vscode bug. Ref - https://github.com/microsoft/vscode/issues/115730
