### ISSUE TITLE
Shadow is much too heavy on the collection and other dropdown

### ISSUE THREAD

**Issue by Tyriar** [thunderclient/thunder-client-support#732]
**Describe the bug**

This shadow is much heavier than elsewhere in the UI:

![image](https://user-images.githubusercontent.com/2193314/185492852-fc19fbd9-9d13-4ab2-910c-c6b1b39a5184.png)

Here's how dropdown like that should look (on my theme Sapphire):

![image](https://user-images.githubusercontent.com/2193314/185492975-30483668-7bfe-4682-aa46-d31ebc2a5fbe.png)

I believe theme keys are available to pull these shadow colors from

**Comment by rangav** [comment]
Thanks @Tyriar for the feedback, Will fix it asap.
