### ISSUE TITLE
404 Errors (even though the same request works from postman)

### ISSUE THREAD

**Issue by lukewis** [thunderclient/thunder-client-support#829]
**Describe the bug**
I'm getting a 404 error when sending a request to localhost.  However, the same request works find from postman

**Platform:** 
 - OS: MacOS 12.5.1
 - vscode version: 1.72.0
 - extension version: 1.19.7

**Question**
- Are there some log files or general troubleshooting steps I should follow?

**Solution:**

**Comment by rangav** [comment]
Hi @lukewis thanks for reporting the issue.

To see logs, open `output` window and select `Thunder Client` in dropdown

**Comment by rangav** [comment]
sometimes could be http library issue, you can change to `axios`, let me know if that works

<img width="427" alt="Screenshot 2022-10-09 at 11 14 33" src="https://user-images.githubusercontent.com/8637550/194751100-a4933269-acaa-4cfa-b64f-7b9a48ee5d05.png">

**Comment by lukewis** [comment]
Thanks for the reply @rangav!  The error logs don't show anything unusual.  I tried axios with the same result (404).  The really weird thing is that my buddy and I share the same git repo, and this request works normally on his machine.  It's broken on mine for some reason.  Other info.  A request to https://google.com works normally.  It seems to only be localhost that's impacted.

**Comment by rangav** [comment]
can you share a srcreenshot if possible, to see if I can find anything unusual.

or try re-starting your machine.

**Comment by rangav** [comment]
try these suggestions in below comments
https://github.com/rangav/thunder-client-support/issues/170#issuecomment-1006233050
https://github.com/rangav/thunder-client-support/issues/170#issuecomment-1096268558

or try the below urls

- `http:// 127.0.0.1:8008/`
-  `[::1]:8008/`
