### ISSUE TITLE
Couldn't resolve the hostname to an ip address

### ISSUE THREAD

**Issue by muldon** [thunderclient/thunder-client-support#852]
Thunder client can´t connect to make requests to local virtual hosts when using  traefik. The same URL opens in the browser. 
 
**Platform:** 
 - OS: MAC
 - vscode version: 1.72.2
 - extension version: 1.20.1

**Comment by rangav** [comment]
sometimes could be http library issue, you can change to `axios` using vscode setting, let me know if that works

<img width="427" alt="Screenshot 2022-10-09 at 11 14 33" src="https://user-images.githubusercontent.com/8637550/194751100-a4933269-acaa-4cfa-b64f-7b9a48ee5d05.png">

**Comment by rangav** [comment]
try these suggestions in below comments
https://github.com/rangav/thunder-client-support/issues/251#issuecomment-874439967
https://github.com/rangav/thunder-client-support/issues/170#issuecomment-1096268558
https://github.com/rangav/thunder-client-support/issues/170#issuecomment-864047143

or try the below urls

- `http:// 127.0.0.1:8008/`
-  `[::1]:8008/`
