### ISSUE TITLE
Instance settings for environments

### ISSUE THREAD

**Issue by davinishi** [thunderclient/thunder-client-support#925]
### Discussed in https://github.com/rangav/thunder-client-support/discussions/610

<div type='discussions-op-text'>

<sup>Originally posted by **davinishi** June  1, 2022</sup>
Something I never seen on any client is a parameter settting for multiple instances environments.

E.g: 
Some companies have multiple instances running for each system: development, preproduction, prouction, etc.
Today, the standard environment variables allow us to set different URL's, usernames, passwords, etc, though we have to create one 
environment for each instance, in this example, 3 environments at least, each environment with the same amount of variables with different values corresponding to the correct instance of the server.

Idea: Instead of having the conventional Environment Variables, it could be easier if a dynamic variable could have multiple values, so when setting the active Environment, we could set also a second parameter like "Instance".

The configuration would look like this but of course there are better ui than that:

![image](https://user-images.githubusercontent.com/106403530/171457293-3855e74e-e512-4068-92ae-e870c4c0c194.png)

</div>

**Comment by rangav** [comment]
@davinishi thanks for the feedback, 

this looks more complicated than regular environments setup
