### ISSUE TITLE
OpenAPI/Swagger schema/format export

### ISSUE THREAD

**Issue by gaufranc** [thunderclient/thunder-client-support#963]
**Is your feature request related to a problem? Please describe.**
We currently cannot export our collections as OpenAPI/Swagger schema/format

**Describe the solution you'd like**
I would like to have the ability to export as OpenAPI/Swagger schema/format, since it allows us to create docs automatically, and much more.

Thanks!

**Comment by rangav** [comment]
@gaufranc thanks for creating feature request.

Can I know what is your team size using TC?

**Comment by gaufranc** [comment]
@rangav Sorry i forgot to add, my team size is 5 ppl at the moment

**Comment by rangav** [comment]
Thanks for sharing info

**Comment by rangav** [comment]
As an alternative solution, you can convert thunder client collection to Postman collection and then use tool to convert postman to openApi/swagger format

**Comment by gaufranc** [comment]
Yes, that was what we're doingright now, but would be useful to do it directly in the extension though :)

**Comment by rangav** [comment]
ah thats good, at least you are not blocked. Will add this feature to roadmap.

**Comment by gaufranc** [comment]
Thanks @rangav !

**Comment by raf202** [comment]
Any updates on this? I've seen Open API import on the documentation, but no export.

**Comment by va2dim** [comment]
@rangav any update? As no direct method to export to OpenAPI
export collection to Postman, but route description that present in export file not imported to Postman.

**Comment by davidkhess** [comment]
Also interested in this. Since Thunder Client doesn't have any documentation generation features, this would make it possible to take the collection to other documentation tools.

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.29.5.`

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.29.5

The feature is in `Beta`, Please test it and let me know your feedback

**Comment by skylinesales** [comment]
///
