### ISSUE TITLE
Conflicting VS Code keybindings to show Thunder Client

### ISSUE THREAD

**Issue by Haltarys** [thunderclient/thunder-client-support#966]
**Describe the bug**
I can't use the keyboard shortcut `Ctrl+Shift+R` to refactor my code because it is shadowed by this extension.

**To Reproduce**
1. Install Thunder client.
2. Open a text editor (with `Ctrl+N` for example)
3. Press  `Ctrl+Shift+R`. The Thunder Client opens instead of showing the refactor pop-up.

**Expected behavior**
I should be able to use the extension AND the refactor keyboard shortcut.

**Potential solution**
Either change the keybinding to another combination altogether or add a [`when`](https://code.visualstudio.com/api/references/when-clause-contexts) expression to restrict it to a context where it does not shadow any other keybindings.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.74.2
 - extension version: 2.3.0

**Your Team Size Using TC:**

**Comment by rangav** [comment]
Thanks @Haltarys Thanks for the feedback, will review it.

You can change the shortcut to different key in `keyboard shortcuts` view

**Comment by FranciscoMoretti** [comment]
In case it helps, here are some instructions.

The extension uses `ctrl+shift+r` as the keyboard shortcut, which is the reserved VS Code shortcut for refactor. The extension will override it. To preserve the refactor shortcut, open the shortcut settings by pressing `ctrl+shift+p` and selecting `Open Keyboard Shortcuts (JSON)`. Then add this as a key binding:

```json
{
  "key": "ctrl+shift+r",
  "command": "editor.action.refactor"
}
```
